### PR TITLE
Add PHP 7.1.0-alpha.1 core formula (php71)

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

As per https://github.com/Homebrew/homebrew-php/issues/3271.

Known issues with PHP 7.1.0 alpha1:

 - xdebug won't compiled due to bug with `php_log_err macro` https://bugs.xdebug.org/view.php?id=1314#c3635 (already fixed in https://github.com/php/php-src/commit/d2bc82586b67882fdcdabac8e05cfbb4104bfd47).

 While this is already fixed less likely we need to patch php ourselves for that, based on [7.1 release schedule](https://wiki.php.net/todo/php71) next alpha will be available on Jun 23 2016, so we can ignore this bug or wait for alpha2 or apply that fix in fork or beg for alpha1.5.

### CODE REVIEW

**Comment by javian** [comment]
As far as the header checks go I can see the same error coming up in `brew audit --strict --online php70` so I wouldn't worry about that for now.

**Comment by pinepain** [comment]
Yeah, that's expected. Should formulae goes within the same PR? 

After I started to build formulae, I had to patch php itself to have xdebug and use some non-tagged versions, like for php-ast. While it's ok for alpha version, I doubt to add them into core tap. On the other hand having and maintaining own tap, e.g. pinepain/php71 may limit php71 adoption. Any suggestions?

**Comment by javian** [comment]
Lets keep the core formula seperate and it can be merged. As far as the extensions and modules go I think we should only add the formulas the work and exclude xdebug for instance until there's an officially released version that properly supports it - it is alpha software after all =).

**Comment by pinepain** [comment]
Yeah, that's good idea to merge just core formula first. Let's do it.
 
-----
All below is for the future PR with 7.1 formulae.

Xdebug itself has php 7.1 support, that's solely `php.h` header problem (see description in PR message). In my github fork I applied fix to php 7.1 branch and rolled custom alpha 1.5 release. Basically in my tap it's known to work (see https://github.com/pinepain/homebrew-php fork). Another issue is that php-ast version that adds 7.1 support not yet tagged to I referred to tag. Some other packages like phan depends on it. Once again, for alpha-quality software it's fine, imo. And without xdebug running on alpha version might not be a reasonable solution, personally in my tasks, developing without xdebug not a good idea. In case we decide to go with my custom php7.1 alpha1.5 release (https://github.com/pinepain/php-src/releases/tag/php-7.1.0alpha1.5) that can be done in different PR or we can delay release to wait for alpha2 which should be on Jun 23 2016.

**Comment by javian** [comment]
Thanks for the PR @pinepain - I think it would be best to wait for the official release so its more manageable and we don't mix in too much custom changes.

**Pull request closed without merging**
