### PR TITLE
Update php5 sodium version

### PR DESCRIPTION
**Pull request by jamesthomasonjr**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jamesthomasonjr** [comment]
Removed the php53 changes since it fails on High Sierra

**Comment by SMillerDev** [comment]
Thanks for the PR, everything looks fine. One thing though, could you reword your commit to be more in line with the `<forumula>: <version>` style we normally use for updates? 

_I'd suggest php5-sodium: 1.2.0_

Thanks!

**Comment by jamesthomasonjr** [comment]
No problem, I reworded the commit message to the suggestion 👍

**Comment by javian** [comment]
Thanks @jamesthomasonjr !

**Pull request closed without merging**
