### PR TITLE
Update drush to 8.1.14

### PR DESCRIPTION
**Pull request by daften**
- [X ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the PR, almost ready to merge it but could you reword your commit to `<formula name> <version>`?

**Comment by daften** [comment]
@SMillerDev Should be done now :)

BTW: I see there are still old branches open, e.g. drush 8.1.12 ;)

**Comment by SMillerDev** [comment]
Thanks @daften !

also, I don't see those?

**Comment by alcaeus** [comment]
@SMillerDev check https://github.com/Homebrew/homebrew-php/branches/stale ;)

**Comment by SMillerDev** [comment]
I refuse...

**Comment by daften** [comment]
Ok then, image here: 
screen shot 2017-10-16 at 16 21 13

:p

**Pull request closed without merging**
