### PR TITLE
composer@1.2 (new formula)

### PR DESCRIPTION
**Pull request by arnested**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----
A versioned composer. Version 1.2.4 -- the last version before composer
changed its date format.

### CODE REVIEW

**Comment by javian** [comment]
Thanks for the submission @arnested . Can you please change this into @1.2 instead of @1.2.4 - this seems to be the general way to do it and would be the best in case there was a bugfix ever released for it.

**Comment by javian** [comment]
Also do you have any external reference to the problem you are describing and the change of the date format ?

**Comment by arnested** [comment]
Hi @javian,

I changed it to `@1.2` as suggested.

Composer changed it date format from
```
"time": "2017-01-06 14:33:56"
```
to
```
"time": "2017-01-06T14:33:56+00:00"
```
in version `1.3.0`.

If cooperating with other people who are (for some reason) stuck on an older version will lead to either inconsistent timestamps in `composer.lock` or pull requests changing a lot of lines unnecessary. This gives Homebrew users the choice to stay behind together with the people stuck on the old version.

**Comment by javian** [comment]
@arnested I'm thinking we should add a caveat definition just to say that the binary/phar name is different don't you think just to be explicit about it. What do you think ?

**Comment by arnested** [comment]
@javian, Makes sense. I have added a short caveats. Feel free to suggest another text for it.

**Comment by javian** [comment]
@arnested looks good, lets run with that. Thank you!

**Pull request closed without merging**
