### PR TITLE
PHP Code Sniffer 2.6.1

### PR DESCRIPTION
**Pull request by Zifius**

### CODE REVIEW

**Comment by javian** [comment]
It looks like one of the inreplace commands needs to be rewritten to pass the tests.

**Comment by Zifius** [comment]
@javian yeah, do you have any hints how to fix? Not a ruby expert and by googling didn't reveal much

**Comment by javian** [comment]
Yes I do but I need to post that later unless someone else does it before me.

**Comment by javian** [comment]
You should be able to remove the do |s| part , remove s.gsub and end and put everything on one line. It should look like the inreplace line a few lines above the failing one.

**Comment by Zifius** [comment]
Thanks for the hint @javian. All green now 👍

**Comment by javian** [comment]
Perfect ! Then we can get it on board. @ablyler if you are online can you merge this otherwise I'll do it in a couple of hours.

**Comment by javian** [comment]
Thanks for the PR @Zifius !

**Comment by Zifius** [comment]
Happy to help!

**Pull request closed without merging**
