### PR TITLE
Update to PHP 7.0.0-rc.5

### PR DESCRIPTION
**Pull request by EspadaV8**

### CODE REVIEW

**Comment by ablyler** [comment]
Thanks, I've used your commit to create pull request #2472 which also regenerates some other formulas.

**Comment by EspadaV8** [comment]
Ah, thanks, didn't realise that needed doing. For future reference how would I know what other formulas need regenerating and how would I go about regenerating them?

**Comment by EspadaV8** [comment]
Ah, is it related to the first section here? https://github.com/Homebrew/homebrew-php/wiki/Bottles 

> To start, bump the version numbers in Abstract/abstract-php.rb and get merged into the repository. Then, in Formulas/php53.rb, Formulas/php54.rb, Formulas/php55.rb, and/or Formulas/php56.rb, empty the bottle do block. Save and submit as a Pull Request. Once the Brew test bot has built new bottles, merge the PR with the bottles with the --bottle option (note: you must have access to the homebrew-php project in Bintray in order to do so)

Sorry about that. I should've read the wiki beforehand.

**Comment by ablyler** [comment]
@EspadaV8 no worries

**Pull request closed without merging**
