### PR TITLE
php-maxminddb 1.2.0 (except php 5.3)

### PR DESCRIPTION
**Pull request by dasmfm**
- [+] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by dasmfm** [comment]
@BrewTestBot test it please.

**Comment by SMillerDev** [comment]
@BrewTestBot test it please.

**Comment by SMillerDev** [comment]
@BrewTestBot Test this please !

**Comment by SMillerDev** [comment]
Looks good @dasmfm could you just change the commit name to the format `<formula name> <new version>` so in this case that would be`php-maxminddb 1.2.0`?

**Comment by SMillerDev** [comment]
Thanks @dasmfm !

**Pull request closed without merging**
