### PR TITLE
PHP 5.6.25 core extension bottle update

### PR DESCRIPTION
**Pull request by javian**

### CODE REVIEW

**Comment by javian** [comment]
Having problems with the build bot again.

**Comment by ablyler** [comment]
@javian no need to create revisions, as the version will change due to it pulling it in from the abstract.  also, i'll create separate PRs for each formula right now to get around the build bot issue.

**Comment by javian** [comment]
@ablyler I think revisions make it easier to manage though. If a new version is released just update the revision and off we go. At least it makes more sense than adding a space to the end of the file imo =)

**Comment by javian** [comment]
Since this has been merged through other PRs I will close this.

**Pull request closed without merging**
