### PR TITLE
Update revision for imagemagick-dependent formula

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus ! Magickwand does not compile however since the `imagemagick` formula links to version 7. See https://www.imagemagick.org/script/porting.php#headers for updating it to work with 7 . Not sure if that will suffice though.

**Comment by alcaeus** [comment]
I've changed the magickwand formulae to depend on `imagemagick@6`, which should hopefully fix the build errors. I'd have to make time to see if I can patch magickwand. Looks like the last release was made more than 2 years ago, so I'm not sure what else I'd run into.

**Comment by alcaeus** [comment]
@javian I have no idea why magickwand cannot be built, any suggestions?

**Comment by javian** [comment]
Try updating the `"--with-magickwand=#{Formula["imagemagick"].opt_prefix}",` line with the ...@6 formula and see if that works.

**Comment by alcaeus** [comment]
Oh my. I should check my caffeine levels before working. Thanks!

**Comment by javian** [comment]
Thanks @alcaeus !

**Pull request closed without merging**
