### PR TITLE
Fix PHP5 yac

### PR DESCRIPTION
**Pull request by pd4d10**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

[yac](https://github.com/laruence/yac)'s `master` branch is for PHP7. Use `php5` branch instead.

### CODE REVIEW

**Comment by javian** [comment]
Thanks for the submission @pd4d10 . These formulas should be changed in released versions rather than relying on the head version. Can you fix that ?

**Comment by pd4d10** [comment]
@javian done, also add PHP7 yac https://github.com/Homebrew/homebrew-php/pull/3780

**Comment by pd4d10** [comment]
Hi, @javian, head URL has been changed to PHP5 branch. I don't know much about what `version_scheme 1` means, could you please provide some examples or documentation?

**Comment by javian** [comment]
Here's an example - https://github.com/Homebrew/homebrew-core/pull/4006/files 

The cookbook documentation is here https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#version-scheme-changes

**Comment by pd4d10** [comment]
`version_scheme` added

**Comment by javian** [comment]
Thanks for the submission @pd4d10 !

**Pull request closed without merging**
