### PR TITLE
Add php56-ioncubeloader formula

### PR DESCRIPTION
**Pull request by Zifius**

### CODE REVIEW

**Comment by Zifius** [comment]
@alanthing the IonCube support responded that they don't keep old version on purpose but they offered a checksum feed implementation, though I'm not sure that this is supported in homebrew (I'm primarily PHP developer). If you can shed some insight on how to implement it that would be appreciated

**Comment by alanthing** [comment]
Try removing the `sha1` portions. If it builds locally for you, commit and push and we'll see what the brew bot thinks. It might fail in the audit section, but that'd be okay if it built successfully and we knew it was acceptable for this formula.

**Comment by Zifius** [comment]
@alanthing thanks, php55 built green other versions just resubmitted

**Comment by alanthing** [comment]
Thanks for your work on this!

**Comment by Zifius** [comment]
@alanthing cheers Alan, thanks for your guidance

**Pull request closed without merging**
