### PR TITLE
Add phpXY-kafka

### PR DESCRIPTION
**Pull request by casterx**
I add formula for Kafka Client https://github.com/EVODelavega/phpkafka

Please notice that the upstream https://github.com/salebab/phpkafka is inactive and not supported by the author. It's why we have "GitHub fork (not canonical repository)"

### CODE REVIEW

**Comment by ablyler** [comment]
@casterx looks like `brew audit --strict` is returning the following:
```
 * Please remove the indefinite article "A" from the beginning of the description
 * GitHub fork (not canonical repository)
```

**Comment by casterx** [comment]
@ablyler, I'll fix ` * Please remove the indefinite article "A" from the beginning of the description`

But how can I deal with `* GitHub fork (not canonical repository)`? Because as I said in the description, the upstream of this extension is inactive, and they recommend to use forked version. Are there anyways to bypass that check?

**Comment by ablyler** [comment]
@casterx ah, I missed that. we can just ignore that check then, no worries.

**Comment by casterx** [comment]
@ablyler Thanks, I've just pushed the fix for description :) I believe it's the final error :)

**Comment by ablyler** [comment]
@casterx it looks like brew bot is having issues with the php 5.3 version. can you compile that version locally okay?

**Comment by casterx** [comment]
I installed it locally with PHP 5.3, here is the log

```bash
🍺  [00:52] nhattran@mbp:~ $ brew install php53
==> Installing php53 from josegonzalez/homebrew-php
==> Downloading https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php53-5.3.29_2.yosem

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php53"
Download failed: https://homebrew.bintray.com/bottles-josegonzalez/homebrew-php/php53-5.3.29_2.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing dependencies for josegonzalez/php/php53: re2c, flex, homebrew/versions/bison2
==> Installing josegonzalez/php/php53 dependency: re2c
==> Downloading https://homebrew.bintray.com/bottles/re2c-0.14.3.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring re2c-0.14.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/re2c/0.14.3: 5 files, 364K
==> Installing josegonzalez/php/php53 dependency: flex
==> Downloading https://homebrew.bintray.com/bottles/flex-2.5.39.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring flex-2.5.39.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of flex.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/flex/lib
    CPPFLAGS: -I/usr/local/opt/flex/include

==> Summary
🍺  /usr/local/Cellar/flex/2.5.39: 45 files, 2.0M
==> Installing josegonzalez/php/php53 dependency: homebrew/versions/bison27
==> Downloading https://homebrew.bintray.com/bottles-versions/bison27-2.7.1.yosemite.bottle.1.tar.g
######################################################################## 100.0%
==> Pouring bison27-2.7.1.yosemite.bottle.1.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Some formulae require a newer version of bison.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/bison27/lib

==> Summary
🍺  /usr/local/Cellar/bison27/2.7.1: 36 files, 1.7M
==> Downloading https://php.net/get/php-5.3.29.tar.bz2/from/this/mirror
==> Downloading from https://secure.php.net/distributions/php-5.3.29.tar.bz2
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/ablyler/c0264742cc1cca84b708/raw/a0a733810be241c
######################################################################## 100.0%
==> Patching
patching file Makefile.global
patching file Zend/acinclude.m4
patching file Zend/zend_language_parser.y
patching file acinclude.m4
patching file aclocal.m4
patching file configure
patching file configure.in
patching file generated_lists
patching file main/php_config.h.in
patching file sapi/cgi/Makefile.frag
patching file sapi/cgi/config9.m4
patching file sapi/cli/Makefile.frag
patching file sapi/cli/config.m4
patching file sapi/fpm/Makefile.frag
patching file sapi/fpm/config.m4
patching file sapi/litespeed/Makefile.frag
patching file sapi/litespeed/config.m4
patching file sapi/milter/Makefile.frag
patching file sapi/milter/config.m4
==> ./configure --prefix=/usr/local/Cellar/php53/5.3.29_2 --localstatedir=/usr/local/var --sysconfd
==> make
==> make install
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php5_module    /usr/local/opt/php53/libexec/apache2/libphp5.so

The php.ini file can be found in:
    /usr/local/etc/php/5.3/php.ini

✩✩✩✩ Extensions ✩✩✩✩

If you are having issues with custom extension compiling, ensure that
you are using the brew version, by placing /usr/local/bin before /usr/sbin in your PATH:

      PATH="/usr/local/bin:$PATH"

PHP53 Extensions will always be compiled against this PHP. Please install them
using --without-homebrew-php to enable compiling against system PHP.

✩✩✩✩ PHP CLI ✩✩✩✩

If you wish to swap the PHP you use on the command line, you should add the following to ~/.bashrc,
~/.zshrc, ~/.profile or your shell's equivalent configuration file:

      export PATH="$(brew --prefix homebrew/php/php53)/bin:$PATH"

✩✩✩✩ FPM ✩✩✩✩

To launch php-fpm on startup:
    mkdir -p ~/Library/LaunchAgents
    cp /usr/local/opt/php53/homebrew.mxcl.php53.plist ~/Library/LaunchAgents/
    launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.php53.plist

The control script is located at /usr/local/opt/php53/sbin/php53-fpm

OS X 10.8 and newer come with php-fpm pre-installed, to ensure you are using the brew version you need to make sure /usr/local/sbin is before /usr/sbin in your PATH:

  PATH="/usr/local/sbin:$PATH"

You may also need to edit the plist to use the correct "UserName".

Please note that the plist was called 'homebrew-php.josegonzalez.php53.plist' in old versions
of this formula.

To have launchd start josegonzalez/php/php53 at login:
  ln -sfv /usr/local/opt/php53/*.plist ~/Library/LaunchAgents
Then to load josegonzalez/php/php53 now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.php53.plist
==> Summary
🍺  /usr/local/Cellar/php53/5.3.29_2: 315 files, 45M, built in 3.7 minutes
🍺  [00:57] nhattran@mbp:~ $ brew install php53-kafka
==> Installing php53-kafka from josegonzalez/homebrew-php
==> Installing dependencies for josegonzalez/php/php53-kafka: lzlib, librdkafka
==> Installing josegonzalez/php/php53-kafka dependency: lzlib
==> Downloading https://homebrew.bintray.com/bottles/lzlib-1.7.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring lzlib-1.7.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/lzlib/1.7: 9 files, 152K
==> Installing josegonzalez/php/php53-kafka dependency: librdkafka
==> Downloading https://homebrew.bintray.com/bottles/librdkafka-0.8.6.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring librdkafka-0.8.6.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/librdkafka/0.8.6: 9 files, 684K
==> Installing josegonzalez/php/php53-kafka
==> Downloading https://github.com/EVODelavega/phpkafka/archive/6a0908803ab6e9d862097e99f84aeb0fff9
==> Downloading from https://codeload.github.com/EVODelavega/phpkafka/tar.gz/6a0908803ab6e9d862097e
######################################################################## 100.0%
==> /usr/local/opt/php53/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php53-kafka/rev-6a09088 --with-php-config=/usr/local/opt
==> make
==> Caveats
To finish installing kafka for PHP 5.3:
  * /usr/local/etc/php/5.3/conf.d/ext-kafka.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the kafka module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run "php -i" (command-line "phpinfo()")
  * - Look for the info on the kafka module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php53-kafka/rev-6a09088: 4 files, 60K, built in 14 seconds
🍺  [00:59] nhattran@mbp:~ $```

**Comment by ablyler** [comment]
@casterx thanks! can you squash your commits down to one commit?

**Comment by casterx** [comment]
@ablyler I just did :)

**Pull request closed without merging**
