### PR TITLE
Fix breaking change

### PR DESCRIPTION
**Pull request by michaeljs1990**
The default of 5.6 is failing if you have any other version installed. You should not have to install version 5.6 in order to install composer since it works with as low as php 5.3.

### CODE REVIEW

**Comment by ablyler** [comment]
@michaeljs1990 the default should only be installed if none of the php versions are installed, including php53.  is this not working that way for you?

By the way I made this change to fix travis ci and brew bot issues.

**Comment by BrianGilbert** [comment]
@ablyler I can confirm that it tries to install php56 even when php55 is installed

**Comment by michaeljs1990** [comment]
Yeah, that is how i ran into this as well. I had php55 installed and it keeps failing saying that i need to unlink php55 first and then reinstall.

**Comment by ablyler** [comment]
@michaeljs1990 i went ahead and made a different change that should fix this issue 113588a, thanks for the help

**Comment by michaeljs1990** [comment]
awesome thanks for the fix.

**Pull request closed without merging**
