### PR TITLE
composer: use Phar::loadPhar() instead of passthru()

### PR DESCRIPTION
**Pull request by benjifisher**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by benjifisher** [comment]
This gives a better fix for #3590.

There is also an unrelated change in order to make the change pass `brew audit --strict --online`.

**Comment by javian** [comment]
This seems ok to me so I would suggest we merge this and consider to create a more general solution in the #3725

**Comment by benjifisher** [comment]
I am  having second thoughts about this solution.  Looking more closely at `composer.phar`, I see that it has some lines that test APC version and configuration, and then the lines

```php
Phar::mapPhar('composer.phar');
require 'phar://composer.phar/bin/composer';

__HALT_COMPILER(); ?>
```

followed by the binary part of the archive.  I want to understand the difference between `mapPhar()` and `loadPhar()`, and I want to make sure we do not lose the checks related to APC.

**Comment by javian** [comment]
@benjifisher have you gotten any further with this ?

**Comment by javian** [comment]
No feedback on this so I'm going to close it for now - feel free to reopen if you have any further ideas.

**Comment by javian** [comment]
According to the php docs on mapPhar `mapPhar should be used only inside a phar's loader stub. Use loadPhar to load an external phar into memory.` so I would not use that.

**Pull request closed without merging**
