### PR TITLE
igbinary 2.0.5

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
After removing php 5.3 related formulas, it still has the same error.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
@javian Adding `revision` to `molten` formula seems solve previous error but result in "Build timed out (after 60 minutes). Marking the build as aborted."

**Comment by javian** [comment]
I would suggest that you make two PRs in that case since there are so many formulas involved. One for version 7 and one for 5.

**Comment by BePsvPT** [comment]
I have separated this pull request into three new pull requests, #4626, #4627 and #4628.

**Pull request closed without merging**
