### PR TITLE
Scrypt 1.4 with PHP 7 support

### PR DESCRIPTION
**Pull request by kingkorf**

### CODE REVIEW

**Comment by kingkorf** [comment]
The tests are failing because of GitHub API rate limit... anything I can do about that?

```
==> brew audit homebrew/php/php70-scrypt --strict --online

==> Installing or updating 'rubocop' gem

Successfully installed rainbow-2.1.0

Successfully installed ast-2.2.0

Successfully installed parser-2.3.1.0

Successfully installed powerpack-0.1.1

Successfully installed ruby-progressbar-1.8.1

Successfully installed unicode-display_width-1.0.5

Successfully installed rubocop-0.39.0

7 gems installed

Error: GitHub API Error: API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Try again in 31 minutes 27 seconds, or create a personal access token:

  https://github.com/settings/tokens/new?scopes=&description=Homebrew

and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"

==> FAILED
```

**Comment by kingkorf** [comment]
Scrypt not ready yet.

**Comment by javian** [comment]
This is no longer the latest version. Can you update the PR with 1.4.2 ? If the travis check fails that's ok (depending on the error) but the brewbot needs to pass.

**Comment by kingkorf** [comment]
It fails again, wat about brewbot?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Can you correct the description of the Formula ?

```
homebrew/php/php70-scrypt:
  * Description shouldn't start with an indefinite article (A)
```

**Comment by kingkorf** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @kingkorf it seems to be passing now. Would you mind squashing the commit before I merge it ?

**Comment by kingkorf** [comment]
@javian How do I do that?

**Comment by javian** [comment]
@kingkorf this is a good description https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ . You squash it on your own branch and then push it (you might have to force it since you've changed history) and the changes will be reflected here.

**Comment by kingkorf** [comment]
@javian I'll try that, thanks!

**Comment by kingkorf** [comment]
@javian I think I pulled it off..

**Comment by javian** [comment]
@kingkorf looks like it !

**Comment by javian** [comment]
Thank you for the submission @kingkorf , its now been merged.

**Comment by kingkorf** [comment]
Nice!

**Pull request closed without merging**
