### PR TITLE
php-code-sniffer 3.0.1

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by javian** [comment]
The build fails with 
```
Error: 1 problem in 1 formula
homebrew/php/php-code-sniffer:
  * C: 62: col 12: Prefer `$CHILD_STATUS` from the stdlib 'English' module (don't forget to require it) over `$?`.
```
Do you know what causes it ?

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by Zifius** [comment]
Can you please merge @javian?

**Comment by javian** [comment]
Thanks @BePsvPT !

**Pull request closed without merging**
