### PR TITLE
Add php70-zmq formula

### PR DESCRIPTION
**Pull request by jenssegers**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

Add php70-zmq formula, currently only available in `--HEAD`. Feedback is welcome!

### CODE REVIEW

**Comment by javian** [comment]
There's an archive on pecl that you can use instead that supports php7.

**Comment by javian** [comment]
Ping @jenssegers ^^

**Comment by jenssegers** [comment]
@javian I don't really know how to use the pecl archive. I have tried adding it as the `url` but it doesn't want to extract it :)

**Comment by javian** [comment]
You need the URL and the SHA lines. You can generate the sha line like this http://stackoverflow.com/questions/32673943/how-to-update-homebrew-sha256

**Comment by javian** [comment]
@jenssegers did you manage to have a look at this ?

**Comment by javian** [comment]
I will close this issue if its not been addressed within two week. @jenssegers if you want this added then please amend the PR and ask if you need any support - you're almost there!

**Comment by javian** [comment]
No response from OP, closing.

**Pull request closed without merging**
