### PR TITLE
composer 1.4.2

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by BePsvPT** [comment]
same problem as #4158

**Comment by javian** [comment]
Yup, this is a bug in brew that needs to be fixed before this will work. https://github.com/Homebrew/brew/issues/2650

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @BePsvPT !

**Pull request closed without merging**
