### PR TITLE
phan 0.8.4

### PR DESCRIPTION
**Pull request by adambaratz**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by javian** [comment]
Looks like this version bump ran into some issues in the CI
```
==> Verifying phan@0.8-0.8.4.tar.gz checksum
tar xzf /Users/brew/Library/Caches/Homebrew/phan@0.8-0.8.4.tar.gz
==> composer --verbose --no-interaction install
[32mLoading composer repositories with package information[39m
[32mInstalling dependencies (including require-dev) from lock file[39m
Dependency resolution completed in 0.000 seconds
[37;41mYour requirements could not be resolved to an installable set of packages.[39;49m

  Problem 1
    - The requested PHP extension ext-ast ^0.1.4 has the wrong version (0.1.1) installed. Install or enable PHP's ast extension.


==> Formula
Tap: homebrew/php
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/phan@0.8.rb
==> Configuration
```
Do you know what could cause that ?

**Comment by adambaratz** [comment]
Ah, there was a change to the package to require a later version of another package. php71-ast has it, php70-ast doesn't. Let me see if the latter can be updated.

Apologies for not testing this thoroughly.

**Comment by adambaratz** [comment]
See #4221. I'll retest once that change checks out.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
If you want to submit a PR against this again then please follow the convention
```
Warning: Nonstandard bump subject: phan 0.8.4
Warning: Subject should be: phan@0.8 0.8.4
```
Thanks!

**Pull request closed without merging**
