### PR TITLE
php-couchbase: update to 2.3.2

### PR DESCRIPTION
**Pull request by avsej**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@avsej can you please fix these errors ?
``` 
==> FAILED
Error: 2 problems in 1 formula
homebrew/php/php71-couchbase:
  * macOS has been 64-bit only since 10.6 so ENV.universal_binary is deprecated.
  * macOS has been 64-bit only so build.universal? is deprecated.
```

**Comment by avsej** [comment]
@javian I removed lines with `ENV.universal_binary`. Is it enough?

**Comment by javian** [comment]
@avsej doesn't look like it. If you check the CI logs you can see this
```
/bin/sh /private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/libtool --mode=compile clang -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2 -DPHP_ATOM_INC -I/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/include -I/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/main -I/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2 -I/usr/local/Cellar/php53/5.3.29_7/include/php -I/usr/local/Cellar/php53/5.3.29_7/include/php/main -I/usr/local/Cellar/php53/5.3.29_7/include/php/TSRM -I/usr/local/Cellar/php53/5.3.29_7/include/php/Zend -I/usr/local/Cellar/php53/5.3.29_7/include/php/ext -I/usr/local/Cellar/php53/5.3.29_7/include/php/ext/date/lib -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/src/couchbase/authenticator.c -o src/couchbase/authenticator.lo 
/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/couchbase.c:749:32: error: use of undeclared identifier 'PHP_JSON_OBJECT_AS_ARRAY'
                    options |= PHP_JSON_OBJECT_AS_ARRAY;
                               ^
/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/couchbase.c:772:13: error: use of undeclared identifier 'PHP_JSON_OBJECT_AS_ARRAY'
            DECODE_JSON;
            ^
/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/couchbase.c:693:24: note: expanded from macro 'DECODE_JSON'
            options |= PHP_JSON_OBJECT_AS_ARRAY;                                                                       \
                       ^
/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/couchbase.c:804:9: error: use of undeclared identifier 'PHP_JSON_OBJECT_AS_ARRAY'
        DECODE_JSON;
        ^
/private/tmp/php53-couchbase-20170502-53788-939d4a/couchbase-2.3.2/couchbase.c:693:24: note: expanded from macro 'DECODE_JSON'
            options |= PHP_JSON_OBJECT_AS_ARRAY;                                                                       \
                       ^
3 errors generated.
make: *** [couchbase.lo] Error 1
make: *** Waiting for unfinished jobs....
```
do you know what that's about ?

**Comment by javian** [comment]
In #4035 you said that php5.3 was not supported anymore so that might be it.

**Comment by avsej** [comment]
exactly. we dont support 5.3

**Comment by javian** [comment]
Ok, then take out the version bump for 5.3 and leave that formula as it is and it should pass.

**Comment by javian** [comment]
Thanks @avsej !

**Pull request closed without merging**
