### PR TITLE
Add GEOS PHP bindings

### PR DESCRIPTION
**Pull request by mcuelenaere**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

```
homebrew/php/php56-geos:
  * Head-only (no stable download)
Error: 1 problem in 1 formula
```
NOTE: [upstream](https://git.osgeo.org/gogs/geos/php-geos) does not provide tags nor releases at the moment

### CODE REVIEW

**Comment by javian** [comment]
Reached out to @strk to check if we can get a tagged release

**Comment by strk** [comment]
See https://git.osgeo.org/gogs/geos/php-geos/issues/10 for tracking a release tag.
It is waiting for some test reports, can the build status of this PR serve the purpose ? (it's currently failing)

**Comment by javian** [comment]
The build works but the reason it fails is because the Formula is a so called "head-only" formula and therefore the audit process flags the build as failing. https://travis-ci.org/Homebrew/homebrew-php/builds/153515320 - all errors point to the audit as far as I can tell.

**Comment by javian** [comment]
I checked more closely now and it did not build at all. The CI system require a tagged release so its a bit of a catch 22 =)

**Comment by javian** [comment]
I can also mention that I noticed that `brew install geos --with-php` installs the php extension inside the geos directory. Not as convenient as it would be to have it included here though imo.

**Comment by strk** [comment]
1.0.0rc1 tagged: https://git.osgeo.org/gogs/geos/php-geos/releases

**Comment by javian** [comment]
@mcuelenaere can you please make the formula update ?

**Comment by mcuelenaere** [comment]
@javian yes, I added PHP support to the `geos` formula. However it requires to be installed as `brew install geos --with-php --env=std --no-sandbox` and breaks everytime `PHP` or `geos` is upgraded. Also it cannot use bottles, hence I created a PR for php-geos.

v1.0.0rc1 support has been added!

**Comment by mcuelenaere** [comment]
Jenkins gives:
```
Error: 1 problem in 1 formula
homebrew/php/php71-geos:
  * The homepage is not reachable (curl exit code 28)
```

But AFAICS https://git.osgeo.org/gogs/geos/php-geos is reachable..

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@mcuelenaere I'll rerun the build - it might just have been a temporary issue.

**Comment by javian** [comment]
We finally got there @mcuelenaere - thanks for the submission!

**Pull request closed without merging**
