### PR TITLE
php71 7.1.5

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
The core extension are throwing an error due to
```
==> FAILED
Error: 2 problems in 1 formula
homebrew/php/php71-gmp:
  * macOS has been 64-bit only since 10.6 so ENV.universal_binary is deprecated.
  * macOS has been 64-bit only so build.universal? is deprecated.
```
can you please fix that ? Thanks!

**Comment by alcaeus** [comment]
Sorry about that (again). Would it make sense to update all other formulae as well or would you rather have that done as updates come in?

**Comment by javian** [comment]
I think it would make sense to update all other formula since the bot will complain about all the time otherwise. The way its been done do far is that I've picked it up for the formulas that is upgraded.

**Comment by javian** [comment]
and thank you! There's a new 7.0 release out to if you want to tackle that one =)

**Comment by alcaeus** [comment]
> and thank you! There's a new 7.0 release out to if you want to tackle that one

Coming up ;)

> I think it would make sense to update all other formula since the bot will complain about all the time otherwise.

Will do - I'll spread out the pull requests over a few days to avoid overloading the build system like [last time](https://github.com/Homebrew/homebrew-php/pull/2548) 😉

**Pull request closed without merging**
