### PR TITLE
Bump revision for php72-stats

### PR DESCRIPTION
**Pull request by alcaeus**

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
thanks again @alcaeus (final one)

**Comment by alcaeus** [comment]
@SMillerDev I'm lazy, so I waited for this one. Thank you for merging all of these, it is very much appreciated! 🍻

**Comment by SMillerDev** [comment]
So am I, didn't help me much today :smile:

**Pull request closed without merging**
