### PR TITLE
Add php70-yaf

### PR DESCRIPTION
**Pull request by CarloQ**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Can you please point head and the release archive to https://github.com/laruence/yaf ?

**Comment by CarloQ** [comment]
OK~

**Comment by javian** [comment]
The php7 branch does not seem to exist and so we need to use master.

**Comment by CarloQ** [comment]
Sorry... This branch existed 2 days ago...

**Pull request closed without merging**
