### PR TITLE
Update arcanist to release 2017-03-08 revision 1

### PR DESCRIPTION
**Pull request by paladox**
This downloads from the stable branch instead.

- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks for the submission @paladox - I'm sorry but this can't be merged. We need a proper released version to be able to update it.

**Comment by paladox** [comment]
Would using the released of arcanist and libphutil work https://github.com/wikimedia/arcanist/releases ?

they merge upstream version into that repo. Also i've been using wikimedia's version for a while.

**Comment by javian** [comment]
Absolutely. Use https://github.com/wikimedia/arcanist/archive/release/2017-03-08/1.tar.gz or whatever is the latest version, use `version 20170308` with the date minus the dashes since I don't think brew will pick it up automatically.

**Comment by javian** [comment]
Or now that I look at it again add the revision number as well, so use `version 201703081`.

**Comment by paladox** [comment]
Im not sure what you mean by use the revision number?

**Comment by paladox** [comment]
I've added version 201703081

**Comment by javian** [comment]
You need to create the sha and include that.

**Comment by javian** [comment]
Also please name it correctly and use  `arcanist <versionnumber>` in the title and commit message.

**Comment by paladox** [comment]
@javian How do i include the sha please?

**Comment by paladox** [comment]
Done. I've added the sha256.

**Comment by paladox** [comment]
Please note this release has wmf specific hack. Wikimedia will not support this release. Everyone should go upstream for any help.

**Comment by javian** [comment]
Do you have a link to more information about this ?

**Comment by javian** [comment]
Thanks for the submission!

**Comment by paladox** [comment]
Hi, oh, thanks.

Upstream is https://secure.phabricator.com

**Pull request closed without merging**
