### PR TITLE
litmus-cli 0.2.0

### PR DESCRIPTION
**Pull request by k127**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### `litmus-cli` is a…
Command-line interface for [Litmus email testing service](https://litmus.com/)
…integrating Litmus PHP API client ([gee1web/litmus](https://github.com/geelweb/Litmus)) as a Symfony Console Application.

See also: <https://git.dev-digitalmobil.com/klaus/litmus-cli>

### CODE REVIEW

**Comment by k127** [comment]
@javian, could there be an issue with Jenkins? I can't see a hint to a problem of the actual formula in the failed job's log.

**Comment by javian** [comment]
@k127 yes, there also seems to be an issue with the setup in github and the CI integration but I've asked about it so it should go away soon I imagine.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @k127 !

**Pull request closed without merging**
