### PR TITLE
drupalconsole 1.5.0

### PR DESCRIPTION
**Pull request by el7cosmos**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @el7cosmos !

**Pull request closed without merging**
