### PR TITLE
Add php71-ast formula

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Can you please change the version to

`0.1.1.<date of the commit you want to use>`

it won't be able to compare the version numbers otherwise which might break future upgrades.

**Comment by pinepain** [comment]
I asked ast maintainer to tag some version to depend on it, I also don't like to depend on hashes.

**Comment by javian** [comment]
We had a short talk about the versioning comparisons here

**Comment by pinepain** [comment]
According to Nikic, he will do some tests adjustments to match php 7.1 better and then tag it. Let's postpone this PR at this time.

**Comment by javian** [comment]
Sounds good. Thanks for looking into it!

**Comment by pinepain** [comment]
New version 0.1.2 tagged. PR updated. For other phpXY version I will provide separate PR with the updates (I guess it is fine to have all them in one commit, as per our previous discussion).

**Comment by javian** [comment]
Thanks @pinepain ! Merged.

**Pull request closed without merging**
