### PR TITLE
bump php70 to rc2

### PR DESCRIPTION
**Pull request by dennisdegreef**

### CODE REVIEW

**Comment by dennisdegreef** [comment]
Should close https://github.com/Homebrew/homebrew-php/issues/2034

Please let me know if I'm missing something here... I looked at https://github.com/Homebrew/homebrew-php/pull/2008 as an example.

**Comment by hainuo** [comment]
```
-> % brew upgrade php70
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Upgrading 1 outdated package, with result:
homebrew/php/php70 7.0.0-rc.2
==> Upgrading homebrew/php/php70
==> Downloading https://downloads.php.net/~ab/php-7.0.0RC2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/php70-7.0.0-rc.2.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/php70/7.0.0-rc.2 --localstatedir=/usr
checking whether to enable ctype functions... yes
checking for cURL support... yes
checking for cURL in default path... not found
configure: error: Please reinstall the libcurl distribution -
    easy.h should be in <curl-dir>/include/curl/

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-php/issues

Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```
在 10.11下 编译安装报错如上：
Installation at 10.11 compile error as above:

**Comment by hainuo** [comment]
@dennisdegreef

**Comment by ablyler** [comment]
I've added a commit to your pull request to regenerate the bottles, new PR is #2042

**Pull request closed without merging**
