### PR TITLE
Upgrade PHP 5.x Redis to 2.2.8 and PHP 7.x to official 3.0.0 URL

### PR DESCRIPTION
**Pull request by mcuelenaere**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
---

### CODE REVIEW

**Comment by javian** [comment]
I would suggest that you split the PR into two. One for the older version and one for the new version. You also need to update the php71 formula since that doesn't compile since the path is incorrect to the build directory.
```
x phpredis-3.0.0/tests/mkring.sh
Error: No such file or directory - redis-3.0.0
```

**Comment by cheukchiu** [comment]
Please fix this problem, I count on it.

**Comment by javian** [comment]
@cheukchiu Feel free to submit a new PR for this since the OP is not responding.

**Comment by mcuelenaere** [comment]
Deprecated by https://github.com/Homebrew/homebrew-php/pull/3758 and https://github.com/Homebrew/homebrew-php/pull/3759

**Pull request closed without merging**
