### PR TITLE
Add php7x-uv formula

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by pinepain** [comment]
This is head-only formula while there are no tagged version for php7x in a source repo, so it expected to fail. Are there any way to let bot know that this is head-only formula and it should be built with `--HEAD` option?

**Comment by javian** [comment]
No there's no way of telling the bot that as far as I know. This plugin is experimental so is there a good argument why we should include it in homebrew-php ?

**Comment by pinepain** [comment]
There is nice async framework - [amphp/aerys](https://github.com/amphp/aerys) which can use various async io backends, including uv, which shows the best performance. While it is still very experimental, I guess it would be nice to help to spread it usage among users. It will also allow to keep consistence between local dev env and production for those who are on macs.

**Comment by javian** [comment]
I just noticed that if you have installed a HEAD formula it won't upgrade to a regular version if one is provided (php70-redis was a head only formula until now). The regular homebrew upgrade process doesn't tell you at all but if you trigger the upgrade manually it will complain and you can deal with it by removing and reinstalling the module. This might be an OK behaviour if you do install formulas with `--HEAD` .

**Comment by pinepain** [comment]
Interesting. I asked Bob Weinand to tag some version, but from our last talk he planned to do some refactoring (it's kinda constant process to want to do that) and he's not using homebrew.

**Comment by pinepain** [comment]
@javian ptal. php-uv was recently tagged, so I added formulas for both 70 and 71 PHP.

Currently build fails because  `GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)` which seems to be ok.

**Comment by pinepain** [comment]
@javian ping. External issue is resolved: php-uv tagged revision which we now use in this pr. PTAL.

**Comment by pinepain** [comment]
Any chance to give someone a look at it?

**Comment by pinepain** [comment]
@javian ptal this pr, please.

**Pull request closed without merging**
