### PR TITLE
arcanist: Add bash and zsh completions

### PR DESCRIPTION
**Pull request by ChaitanyaPramod**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Install the bash and zsh completions

### CODE REVIEW

**Comment by SMillerDev** [comment]
@ChaitanyaPramod the zsh completions don't really seem like zsh completions to me.

**Comment by ChaitanyaPramod** [comment]
@SMillerDev zsh offers [compatibility](http://zshwiki.org/home/convert/bash#bash_completions) for bash completions which [the common script](https://github.com/wikimedia/arcanist/blob/wmf/stable/resources/shell/bash-completion) makes use of.
I have tested the completions locally on zsh and bash.

**Comment by SMillerDev** [comment]
Maybe you can bump the version as well in a separate commit?

**Comment by ChaitanyaPramod** [comment]
@SMillerDev Have updated the revision.

**Comment by SMillerDev** [comment]
Thanks @ChaitanyaPramod , but now that the update was merged before we have merge conflicts. Can you rebase this branch please?

**Comment by ChaitanyaPramod** [comment]
@SMillerDev It's rebased now.

**Comment by SMillerDev** [comment]
Thanks @ChaitanyaPramod !

**Pull request closed without merging**
