### PR TITLE
Rename deprecated httpd22/httpd24 to httpd

### LINKED ISSUE #4499: `httpd24` is deprecated, cannot build Apache handlers
[Here](https://github.com/Homebrew/homebrew-php/blob/6be8d9b/Abstract/abstract-php.rb#L69-L70) we're using the option `with-httpd22`, however, `httpd24` is deprecated and its new name is `httpd` now, and `httpd22` is non-existant.

Other than that, I don't see a real reason why one shouldn't be able to build PHP's Apache handlers without actually installing the server. OS X has a built in Apache server, so I end up having installed 2 servers.

As it looks right now, this package seems to be completely broken.

```
boro@bor0:~$ brew install php71 --with-httpd
==> Installing php71 from homebrew/php
Warning: homebrew/php/php71: this formula has no --with-httpd option so it will be ignored!
==> Downloading https://php.net/get/php-7.1.8.tar.bz2/from/this/mirror
Already downloaded: /Users/boro/Library/Caches/Homebrew/php71-7.1.8
^C
boro@bor0:~$ brew install php71 --with-httpd24 
==> Installing php71 from homebrew/php
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
==> Installing dependencies for homebrew/php/php71: homebrew/apache/httpd24
Warning: Use httpd instead of deprecated homebrew/apache/httpd24
==> Installing homebrew/php/php71 dependency: homebrew/apache/httpd24
==> Downloading https://homebrew.bintray.com/bottles/httpd-2.4.27_4.high_sierra.bottle.tar.gz
Already downloaded: /Users/boro/Library/Caches/Homebrew/httpd-2.4.27_4.high_sierra.bottle.tar.gz
==> Pouring httpd-2.4.27_4.high_sierra.bottle.tar.gz
```

### PR DESCRIPTION
**Pull request by bor0**
Fixes #4499.

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks @bor0 ! Much appreciated

**Comment by OwenMelbz** [comment]
Has this been merged into an available release yet?

**Comment by SMillerDev** [comment]
As soon as it's merged it's available. Homebrew formula don't use releases.

**Comment by OwenMelbz** [comment]
Okay cool, so no not yet available :D

**Comment by SMillerDev** [comment]
It's merged here: https://github.com/Homebrew/homebrew-php/pull/4500/commits/66031b951522c2beefc439917ad4d66082a4ffbf

**Pull request closed without merging**
