### PR TITLE
php56 5.6.32

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

While running `brew audit` on main php56 formula, the following error appeared:
> Stable: version 5.6.32 is redundant with version scanned from URL

Do we no longer need a version for the formulae?

### CODE REVIEW

**Comment by alcaeus** [comment]
Looks like audit tests fail - do you want me to remove the `version` field from all the formulae update in these PRs?

**Comment by SMillerDev** [comment]
Not sure about the implications of that but it seems to work fine for 7.2 so lets go for it.

**Comment by alcaeus** [comment]
@SMillerDev done!

**Comment by javian** [comment]
Thanks @alcaeus ! The version is automatically detected from the URL nowadays so that's why it complained so yes it was the right decision to remove it.

**Pull request closed without merging**
