### PR TITLE
Update php-sodium to 2.0.7. Needed now that libsodium is at 1.0.15.

### PR DESCRIPTION
**Pull request by moderndeveloperllc**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Not sure how this will interact with #4471, but the changes are to a different are in the file.

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
@SMillerDev Not sure why it's failing. The notice says: `Error: Testing requires the latest version of homebrew/php/php71-sodium`, so I'm not sure how to get past this when I'm updating the version!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by moderndeveloperllc** [comment]
@javian The failures appear to be an issue with the Jenkins environment?
```
Error: php71-sodium: cannot load such file -- /Users/brew/Jenkins/workspace/Homebrew PHP Pull Requests/version/Abstract/abstract-php-extension
```

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @moderndeveloperllc !

**Pull request closed without merging**
