### PR TITLE
php-couchbase: update to 2.3.0

### PR DESCRIPTION
**Pull request by avsej**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Please exclude removing the php53 formula in this commit.

**Comment by avsej** [comment]
Why? We do not support php 5.3, successful build does not mean it work there properly

**Comment by avsej** [comment]
@javian I did all the checks requires in the PR template. Also strictly speaking we don't support php 5.5, but I will assume it will at least work there as we support 5.4 and 5.6

**Comment by javian** [comment]
My point is that I don't want to remove formulas in an upgrade commit - it should be handled separately. I'd also rather have a new version like the one you submitted for 7.1 in a separate commit to be able to pay attention to that specifically and not get in the way for upgrading formulas that already exist. You don't have to change the 7.1 one formula this time since I'm aware of it now.

**Comment by avsej** [comment]
@javian I've updated it. I will remove 5.3 in next PR

**Comment by javian** [comment]
@avsej you also don't have to remove the bottle lines in the PR, the bot will take care of all of that and it makes the commits smaller. thanks for the submission!

**Pull request closed without merging**
