### PR TITLE
swoole: update v2.0.7 bottle.

### PR DESCRIPTION
**Pull request by xutl**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@xutl you do not have to remove the bottle lines in the formula - they will be automatically adjusted by the build bot.

**Comment by xutl** [comment]
@javian I'm sorry I did not know that the bottle, I deleted the normal use, so it deleted.

**Comment by xutl** [comment]
@javian Do i need to redo it?

**Comment by javian** [comment]
@xutl no, there was just something wrong with the bottle build but I'm waiting to redo that now before I can merge it.

**Comment by javian** [comment]
Thanks @xutl !

**Pull request closed without merging**
