### PR TITLE
php70 7.0.19

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@alcaeus it seems like this is taking too long. I would suggest we split php and the modules into seperate commits.

**Comment by alcaeus** [comment]
@javian I've removed changes to the other formulae, I'd create revision bump pull requests once this PR is merged.

**Comment by javian** [comment]
Thanks @alcaeus ! Can you commit the modules as well ?

**Pull request closed without merging**
