### PR TITLE
Support for macOS Sierra

### PR DESCRIPTION
**Pull request by javian**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@ablyler we're you looking at merging this ? I can't do it at the moment since I'm not in front of my mac but I could take care of it later tonight.

**Comment by javian** [comment]
There are still some concerns for the bottle build of El Cap and Yosemite for 7.0 in the PR but it might just be that the extensions needs to be revisioned and it should work but that's currently untestested at least by me.

**Comment by ablyler** [comment]
@javian i don't think that we have to require the homebrew apache install for macOS Sierra

**Comment by javian** [comment]
@ablyler compiling the apache module requires apxs which no longer exists in Sierra so I think we do. We could make it  `=> :build` though

**Comment by javian** [comment]
@ablyler do you want to take a look at this ?

**Pull request closed without merging**
