### PR TITLE
php70-gearman 2.0.3

### PR DESCRIPTION
**Pull request by localheinz**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
-----

This PR

* [x] updates gearman for PHP 7.0

💁‍♂️ For reference, see https://github.com/wcgallego/pecl-gearman/compare/gearman-2.0.1...gearman-2.0.3.

In regard to building the formula locally, I have no idea how to do that - can anyone help (update the wiki)?

### CODE REVIEW

**Comment by javian** [comment]
Hi @localheinz - thanks for your pull request. There seems to be some major issues with the build of this at least on the build bot. To build the formula locally you need to edit the formula file just as you did and then either `brew upgrade php70-gearman` or remove gearman and then reinstall it again.

If it can't find the bottle for any reason of the new version then you need to force the source build by adding `-s` to the command line. Can you see if you get any errors when trying to build it locally ?

**Comment by localheinz** [comment]
@javian 

Thank you for your feedback, I appreciate it!

The problem is, I have no idea how to get started after

* I have cloned the repository
* I have updated the formula

How do I link the formula in the cloned repository to my `brew` installation?

**Comment by localheinz** [comment]
Ha, I think here's what was needed

```
$ brew untap homebrew/php
$ brew tap localheinz/php
```

Then I checked out the corresponding branch in the tap, and ran


```
$ brew install php70-gearman

==> Installing php70-gearman from localheinz/php
==> Downloading https://github.com/wcgallego/pecl-gearman/archive/gearman-2.0.2.tar.gz
==> Downloading from https://codeload.github.com/wcgallego/pecl-gearman/tar.gz/gearman-2.0.2
######################################################################## 100.0%
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-gearman/2.0.2 --with-php-config=/usr/local/opt/php70/bin/php-config --with-gearman=/usr/local/opt/gearman
==> make
Last 15 lines from /Users/am/Library/Logs/Homebrew/php70-gearman/03.make:
duplicate symbol _gearman_task_obj_handlers in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_client_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_exception_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
duplicate symbol _gearman_task_ce in:
    .libs/php_gearman.o
    .libs/php_gearman_task.o
ld: 20 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [gearman.la] Error 1

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
localheinz/php
```

Not sure, what the problem is, though.

**Comment by localheinz** [comment]
@wcgallego

Do you have an idea?

**Comment by wcgallego** [comment]
Ah, sorry friends. I have an issue open for this too:
https://github.com/wcgallego/pecl-gearman/issues/36

Haven't the bandwidth I'd like to fix this yet, but I think that's my next priority. Thanks for highlighting!

**Comment by localheinz** [comment]
Thanks a ton, @wcgallego!

**Comment by wcgallego** [comment]
just as a follow up - finally merged this in. h/t to @xalopp for doing the heavy lifting!

**Comment by javian** [comment]
@wcgallego will you be posting a new release with this fix included ?

**Comment by javian** [comment]
@localheinz can you update to 2.0.3 ?

**Comment by localheinz** [comment]
Ha, sorry, going to take a look!

**Comment by localheinz** [comment]
After updating, I ran the following steps (apologies, still a total newbie when coming to contributing here):

```
$ brew untap homebrew/php
$ cd /usr/local/Homebrew/Library/Taps/localheinz/homebrew-php
$ git remote set-url origin git@github.com:localheinz/homebrew-php.git
$ git fetch
$ git checkout fix/php70-gearman
$ brew tap --repair
$ brew audit --strict --online php70-gearman
```

Then, following http://stackoverflow.com/a/32753064/1172545 I ran

```
$ brew fetch php70-gearman --build-from-source
```

and used the `SHA256` to update the formula, amended the commit, and pushed again, and then I ran

```
$ brew install php70-gearman
```

which yielded

```
==> Installing php70-gearman from localheinz/php
==> Downloading https://github.com/wcgallego/pecl-gearman/archive/gearman-2.0.3.tar.gz
Already downloaded: /Users/am/Library/Caches/Homebrew/php70-gearman-2.0.3.tar.gz
==> /usr/local/opt/php70/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php70-gearman/2.0.3 --with-php-config=/usr/local/opt/php70/bin/php-config --with-gearman=/usr/local/opt/gearman
==> make
==> Caveats
To finish installing gearman for PHP 7.0:
  * /usr/local/etc/php/7.0/conf.d/ext-gearman.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the gearman module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run `php -i "(command-line 'phpinfo()')"`
  * - Look for the info on the gearman module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php70-gearman/2.0.3: 7 files, 104.6K, built in 12 seconds
```

Does this look any good, hehe?

**Comment by localheinz** [comment]
Yay, build has passed!

**Comment by javian** [comment]
Yes that's perfect @localheinz ! Thanks for the submission! Do you know if it also works with 7.1 and would you consider submitting a PR for that too ? And btw, you do not have to touch the bottle block next time - the bot will automatically do that on our behalf so only the version number needs to get updated.

**Comment by localheinz** [comment]
@javian 

Ha, nice, thank you!

Hang on a moment, will give it a try!

**Pull request closed without merging**
