### PR TITLE
php-cs-fixer 2.7.0

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by derrabus** [comment]
Why has this PR been closed?

**Comment by SMillerDev** [comment]
because #4496 supersedes it I guess

**Comment by BePsvPT** [comment]
@derrabus 

When there is new version release and the old pull request has not been merged, the script will automatically close it. I hope that answers your question.

**Comment by derrabus** [comment]
That makes perfect sense, thanks for the explanation.

**Pull request closed without merging**
