### PR TITLE
Remove PHP 5.3 and 5.4

### PR DESCRIPTION
**Pull request by alcaeus**
Discussion can be found in #3686.

Note: I have replaced `php54` in the installation instructions with `php70` but haven't tested it yet.

### CODE REVIEW

**Comment by josegonzalez** [comment]
@javian can you figure out where we need to "boneyard" these to?

**Comment by alcaeus** [comment]
I took a look at the [homebrew-boneyard](https://github.com/homebrew/homebrew-boneyard) repository, we'd completely swamp it with PHP stuff. How about creating a new homebrew-php-boneyard or homebrew-php-unsupported repository and move everything that is no longer supported there?

**Comment by javian** [comment]
@alcaeus I agree that the regular boneyard probably wouldn't be a good option.
My current idea was to add a caveat text about it no longer being supported and separate the core code into a boneyard version of the abstract files so that it could easily be moved at a later stage whilst us being able to ignore older versions in the abstract code. That would also prepare for future bone yarding so we don't get conflicts with abstract-php for instance when transferring the next php version into the boneyard. Alternatively we could rename the abstract file(s) when the bone yarding takes place since the current snapshot ought to work.

**Comment by alcaeus** [comment]
\*bump\*

if someone could create the repository I'd be glad to do the rest of the work of moving the formulae to that other repository so we can remove them from homebrew-php.

**Comment by alcaeus** [comment]
@javian What are we going to do about these? I'm still in favor of removing them once and for all.

**Comment by alcaeus** [comment]
Closing since the problem will solve itself with https://github.com/Homebrew/homebrew-core/pull/16067. It's not worth the rebases.

**Pull request closed without merging**
