### PR TITLE
Bump PHP70 to RC8

### PR DESCRIPTION
**Pull request by dguyon**
Following http://php.net/archive/2015.php#id2015-11-26-1

### CODE REVIEW

**Comment by dguyon** [comment]
How can I fix this ? https://travis-ci.org/Homebrew/homebrew-php/jobs/93318528#L1482

**Comment by ablyler** [comment]
@dguyon those errors are okay for the core php formulas, it would be nice to not make the error, but for now it is okay.

**Comment by ablyler** [comment]
@dguyon can you rebase this branch off of master?

**Comment by dguyon** [comment]
Done

**Pull request closed without merging**
