### PR TITLE
php70-redis 3.1.1

### PR DESCRIPTION
**Pull request by danielbachhuber**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> Have you built your formula locally prior to submission with brew install `<formula>` (where `<formula>` is the name of the formula you're submitting)?

I've simply made the edits through the GitHub web UI. Hope that's alright!

**Comment by danielbachhuber** [comment]
> I've simply made the edits through the GitHub web UI. Hope that's alright!

Didn't realize it was as easy as `brew edit php70-redis` :)

```
local ➜  wp-redis git:(163-test-php-7) brew audit --strict --online php70-redis
local ➜  wp-redis git:(163-test-php-7) echo $?
0
```

**Comment by neutric** [comment]
> Didn't realize it was as easy as `brew edit php70-redis` :)

This one even calculates the hash and opens the PR for you: `brew bump-formula-pr --url=https://github.com/phpredis/phpredis/archive/3.1.1.tar.gz php70-redis`. It doesn't make you coffee, though. ;)

**Comment by danielbachhuber** [comment]
> This one even calculates the hash and opens the PR for you:

Should `brew bump-formula-pr` be listed in the output for `brew` ?

**Comment by neutric** [comment]
By output you mean the help text? `bump-formula-pr` was [introduced](https://github.com/Homebrew/legacy-homebrew/pull/49848) as developer command and bypasses e.g. the local `brew install`step in favor of a speedy formula update, so leaving it in the shadows a bit is probably by intention.

**Comment by danielbachhuber** [comment]
> By output you mean the help text?

Er, to be more clear:

image

Because there's already a `Developers` section with `brew edit`, I'd expect `brew bump-formula-pr` to be displayed there too.

Didn't mean to take this PR off-topic though. Displaying `brew bump-formula-pr` isn't something I feel strongly opinionated about — just an observation.

**Comment by neutric** [comment]
Good point. I was asking myself the same thing when I discovered `bump-formula-pr` a while back. The above is why I assume it is not listed there, I might be wrong though.

**Comment by javian** [comment]
Thanks for the submission @danielbachhuber ! Would you mind also updating the other php-redis versions ?

As far as the documentation goes there are a lot of commands mentioned in the man page which are not covered in the abbreviated version in the on-screen help so I would doubt it would get added. You could always check if there's been previous PRs suggesting this or make one and see how it goes.

**Comment by danielbachhuber** [comment]
> Would you mind also updating the other php-redis versions ?

@javian Sorry, which other `php-redis` versions?

**Comment by alcaeus** [comment]
Not javian, but there are formula files for PHP 5.3-7.1 which all need updating.

**Comment by neutric** [comment]
See #3998.

**Comment by danielbachhuber** [comment]
👍

**Comment by javian** [comment]
@danielbachhuber Sorry I could have been more explicit but its merged now and we're ok but keep it in mind next time if you can. =)

**Comment by danielbachhuber** [comment]
No worries, will do 👍

**Pull request closed without merging**
