### PR TITLE
Fixes libsodium dependency

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
Failing because it's using the bottled version.

Should I remove the bottle section from the formula?

**Comment by cmckni3** [comment]
Thoughts @ablyler?

**Comment by ablyler** [comment]
@cmckni3 what does changing this to a build only dependency fix? I think it needs to be a normal dependency, since it will link against it.

**Comment by cmckni3** [comment]
@ablyler I see. You're absolutely right.

Is there any way to trigger a new bottle of the formula? The current bottle doesn't work on El Capitan.

**Comment by cmckni3** [comment]
Closing. See #2715

**Pull request closed without merging**
