### PR TITLE
php-code-sniffer@2.9

### PR DESCRIPTION
**Pull request by Zifius**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

@javian Adding versioned formulae as newest 3.0 is a major upgrade and it will take some time until sniffs will catch up

### CODE REVIEW

**Comment by javian** [comment]
Can you have a look at the errors and fix them ?

**Comment by Zifius** [comment]
@javian Already did, it's my first versioned formulae so please bear with me

**Comment by Zifius** [comment]
@javian Any hints how to fix the alias error, that has to be done in the 3.0 formulae, right?

**Comment by Zifius** [comment]
@javian I give up it for now, there seem to be recent changes https://github.com/Homebrew/brew/commit/b14f1572b7ee3b04593bde5d52e14a36aea8d701 to audit.rb which wouldn't allow tests to pass:

```brew audit homebrew/php/php-code-sniffer --strict --online
homebrew/php/php-code-sniffer:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Aliases
      ln -s ../Formula/php-code-sniffer.rb php-code-sniffer@3.0
  * Formula has invalid versioned aliases:
      homebrew/php/php-code-sniffer@3.0
Error: 2 problems in 1 formula
```

The same error happens for e.g. composer formulae

**Comment by Zifius** [comment]
@MikeMcQuaid Any idea what I'm doing wrong here? The audit message doesn't help much

**Comment by MikeMcQuaid** [comment]
@Zifius Looks like a false positive, I'll take a look. You've done the right thing here as far as I can tell.

**Comment by Zifius** [comment]
Alright, thanks for looking into

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by Zifius** [comment]
@javian Should be ok to merge now

**Comment by javian** [comment]
Yeah! Thanks @Zifius.

**Comment by Zifius** [comment]
Cheers @javian! Thanks for raising audit issue properly

**Pull request closed without merging**
