### PR TITLE
AbstractPhpPhar: use a PHP script instead of a bash script for the executable

### PR DESCRIPTION
**Pull request by benjifisher**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

### CODE REVIEW

**Comment by benjifisher** [comment]
This is an alternative to PR #3724 to fix Issue #3590.

In PR #3724 only the formula for `composer` is affected.
In this PR, any formula that extends `AbstractPhpPhar` will be affected.

**Comment by bocharsky-bw** [comment]
Works fine with Ansible 👍

**Comment by javian** [comment]
@benjifisher have you tested this with other phar formulas ?

**Comment by benjifisher** [comment]
@javian Not yet.

I recently came across a comment that looks related to this issue. From the FAQ on the project page benmatselby/sublime-phpcs:

> What if I've installed the applications using Homebrew?

> If you have installed php-cs-fixer, phpmd or phpcs via homebrew then please make sure that you define the "*_executable_path" option to the .phar application and not the wrapper script that is placed in your bin folder, as this will cause odd behaviour.

When I have a chance, I will test further and see whether this other issue is, in fact, related.

**Comment by javian** [comment]
These are the phar Formulas currently in the php tap
```
behat.rb
box.rb
codeception.rb
composer.rb
drupalconsole.rb
envoy.rb
foreman.rb
mondrian.rb
n98-magerun.rb
n98-magerun2.rb
pdepend.rb
pharcc.rb
phpab.rb
phpbrew.rb
phpcpd.rb
phpctags.rb
phpdocumentor.rb
phpdox.rb
phploc.rb
phpmd.rb
phpmetrics.rb
phpunit-skeleton-generator.rb
phpunit.rb
pickle.rb
puli.rb
sqlformat.rb
virtphp.rb
```

**Comment by javian** [comment]
phpunit does not work with this patch
```
➜ phpunit
PHP Warning:  require(phar://phpunit-5.6.1.phar/bin/phpunit): failed to open stream: phar error: "bin/phpunit" is not a file in phar "phpunit-5.6.1.phar" in /usr/local/Cellar/phpunit/5.6.1/libexec/phpunit on line 6

Warning: require(phar://phpunit-5.6.1.phar/bin/phpunit): failed to open stream: phar error: "bin/phpunit" is not a file in phar "phpunit-5.6.1.phar" in /usr/local/Cellar/phpunit/5.6.1/libexec/phpunit on line 6
PHP Fatal error:  require(): Failed opening required 'phar://phpunit-5.6.1.phar/bin/phpunit' (include_path='.:') in /usr/local/Cellar/phpunit/5.6.1/libexec/phpunit on line 6

Fatal error: require(): Failed opening required 'phar://phpunit-5.6.1.phar/bin/phpunit' (include_path='.:') in /usr/local/Cellar/phpunit/5.6.1/libexec/phpunit on line 6
```

**Comment by javian** [comment]
PR is not functioning at the moment so closing while waiting for a working fix.

**Pull request closed without merging**
