### PR TITLE
update PHP-7.0.0-rc.8 to released PHP-7.0.0

### PR DESCRIPTION
**Pull request by eaglewu**
SHA256 CHECKSUM

eagle [~/Downloads] → shasum -a 256 php-7.0.0.tar.gz
f0233661060b53dbd6ca7898b1ddc64e99fe5db1bbf6a15a71dc7d0238aa0fbc  php-7.0.0.tar.gz

### CODE REVIEW

**Comment by ruudk** [comment]
:+1:

**Comment by vinkla** [comment]
:+1:

**Comment by kingkorf** [comment]
:+1:

**Comment by TetsuyaUmigoto** [comment]
+1

**Comment by JKapitein** [comment]
:+1:

**Comment by khkramer** [comment]
:+1:

**Comment by abbert** [comment]
:+1:

**Comment by PheRum** [comment]
:+1:

**Comment by ablyler** [comment]
Thanks, but we will wait for the official announcement from PHP before accepting this.

**Comment by vinkla** [comment]
@ablyler https://github.com/php/php-src/releases/tag/php-7.0.0

**Comment by ablyler** [comment]
@vinkla yep, still going to wait for them to give the official go ahead. they have made last minute changes before an announcement.

**Comment by vinkla** [comment]
@ablyler yeah, sounds good. We don't want anything breaking.

**Comment by JohnMaguire** [comment]
:+1:

**Comment by ablyler** [comment]
@eaglewu thanks for the PR! I went ahead and made some changes and created PR #2620.

**Pull request closed without merging**
