### PR TITLE
Add missing dependency for mcrypt

### LINKED ISSUE #3711: mcrypt extension requires libtool
## Description

When installing `php71-mcrypt` from a fresh installation, the following error will be presented:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-mcrypt/mcrypt.so' - dlopen(/usr/local/opt/php71-mcrypt/mcrypt.so, 9): Library not loaded: /usr/local/opt/libtool/lib/libltdl
.7.dylib
  Referenced from: /usr/local/opt/php71-mcrypt/mcrypt.so
  Reason: image not found in Unknown on line 0
```

The error goes away after installing libtool with `brew install libtool`.
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.12 (16A323) |
| **Homebrew Version:** | 1.0.7 |
| **PHP Version in use:** | PHP 7.1.0RC3 |
| **Xcode Version:** | 8.0 (8A218a) |

**Output of gcc -v:**

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Output of php -v:**

```
PHP 7.1.0RC3 (cli) (built: Oct  2 2016 01:05:16) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
```

**Build logs:** 

_None available, installed using bottle._

### PR DESCRIPTION
**Pull request by shadowhand**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?
---

Without `libtool` installed, the mcrypt extension cannot be loaded at
runtime. Appears to only effect PHP 7.1.

Fixes #3711

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @shadowhand !

**Comment by shadowhand** [comment]
Cheers!

**Pull request closed without merging**
