### PR TITLE
README: Remove versions tap, fix spelling+wording

### PR DESCRIPTION
**Pull request by neutric**
Remove deprecated homebrew/versions tap and fix spelling and wording.

### CODE REVIEW

**Comment by javian** [comment]
Thanks for this @neutric . As far as I know you are not required to tap the dupes tap anymore but that might have changed recently - I haven't tested it in a while. Can you confirm that that is the case ?

**Comment by neutric** [comment]
I remember having read something somewhere, but wasn't able to find it just now, so I tried it out by installing another instance of Homebrew to a non-default location (~/homebrew) and then installing something which requires a formula in `homebrew/dupes`.

```bash
% ~/homebrew/bin/brew install htop --with-ncurses
==> Tapping homebrew/dupes
Cloning into '/Users/ah/homebrew/Library/Taps/homebrew/homebrew-dupes'...
```

As you can see, `homebrew/dupes` is tapped automatically. I can't rule out that there is a variable set by my main homebrew installation which influences which/if taps are autotapped.

@ilovezfs probably knows.

**Comment by javian** [comment]
@neutric can you sort out this conflict ? There's been a few changes to the readme file in other commits.

**Comment by neutric** [comment]
I will soon, just short on time atm.

**Comment by neutric** [comment]
@javian Finally fixed. Sorry for the loooooong delay!

**Comment by javian** [comment]
Thanks @neutric ! Better late than never =)

**Pull request closed without merging**
