### PR TITLE
Update php56-apcu.rb

### PR DESCRIPTION
**Pull request by dawehner**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----
APCU always had some sort of issues with locks and caused some crashes on my system with 4.0.8.
Updating to 4.0.11 resolved those issues.

PS. Annoying now I can actually work instead of starting early into the weekend.

More information on https://github.com/krakjoe/apcu/issues/19

### CODE REVIEW

**Comment by ablyler** [comment]
@dawehner can you update the same thing for the other php versions of this?

**Comment by dawehner** [comment]
Good point. I'll do when I get home
On 7 Jun 2016 7:42 p.m., "Andy Blyler" <notifications@github.com> wrote:
>
> @dawehner can you update the same thing for the other php versions of
this?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by ablyler** [comment]
I've added the other versions in PR #3277

**Comment by dawehner** [comment]
Thank you!

**Pull request closed without merging**
