### PR TITLE
Added spress formula

### PR DESCRIPTION
**Pull request by themizzi**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Really just needs a minimum version of php56. Not sure what the best way to declare that is. Or if we just accept the failed build on a php55 base.

**Comment by javian** [comment]
We could always add a caveat stating the requirements. Once php gets merged in to core we should have better options providing a minimum version.

**Pull request closed without merging**
