### PR TITLE
cleanup phpdbg

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pinepain** [comment]
I guess it is less likely that CI will pass with all core formulas touched. Do we need this change and if so, how should we handle this build?

**Comment by javian** [comment]
If the functionality stays the same I think we can just merge it since this doesn't require any bottle rebuilds.

**Comment by pinepain** [comment]
It should. I will review diff once again in the morning and try on different machine all formulas to make sure no hidden whoops introduced.

**Comment by pinepain** [comment]
@javian I looked through and it looks good.

**Comment by javian** [comment]
I'll have a look at this tomorrow @pinepain

**Comment by javian** [comment]
Thanks for the submission @pinepain !

**Pull request closed without merging**
