### PR TITLE
Update PHP 7.1 Redis to official 3.0.0 URL

### PR DESCRIPTION
**Pull request by mcuelenaere**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pinepain** [comment]
Is there any BC-incompatible API changes between 2.x and 3.x redis branches?

**Comment by mcuelenaere** [comment]
@pinepain this PR does not update from 2.x to 3.x, but it merely aligns the download URL with the one which`php77-redis.rb` is using

**Comment by pinepain** [comment]
@mcuelenaere ah, sorry, I was confused a bit by that old pull request.

**Comment by javian** [comment]
Thanks @mcuelenaere !

**Pull request closed without merging**
