### PR TITLE
Bump revisions for imagemagick dependent formulae

### LINKED ISSUE #3842: Getting php71-imagick error
## Description

PHP scripts on the CLI output an error with loading php71-imagick.
Brew is updated and upgraded.
The error is on the `php-v` section.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | 1.1.2
**PHP Version in use:** | 7.1.0
**Xcode Version:**      | 8.1.0.0.1.1476494586

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 7.1.0 (cli) (built: Dec 11 2016 22:53:08) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes #3842 (once again)

### CODE REVIEW

**Comment by javian** [comment]
Look like we need to bump the older php versions as well since htey fail due to the recent jpeg update.

**Comment by alcaeus** [comment]
Shame. Will push those bumps into this pull request as well 👍

**Comment by javian** [comment]
@alcaeus maybe you can remove the older versions from this PR so we can merge it for the more recent php versions asap and then manage the php revisions for older version separately ?

**Comment by alcaeus** [comment]
Done - I believe we've had bumps for 5.5 and newer, so I've just removed 5.4.

I'll take a look at the 5.3 and 5.4 core formulae tomorrow and create revision bumps as necessary.

**Comment by javian** [comment]
Could you include the dmtx extensions ?
```
==> brew linkage --test php56-dmtx
==> FAILED
Missing libraries:
  /usr/local/opt/imagemagick/lib/libMagickCore-7.Q16HDRI.2.dylib
  /usr/local/opt/imagemagick/lib/libMagickWand-7.Q16HDRI.0.dylib
```

**Comment by alcaeus** [comment]
@javian pushed a revision bump for php55-dmtx and php56-dmtx to this branch.

**Comment by javian** [comment]
Thanks @alcaeus !

**Pull request closed without merging**
