### PR TITLE
n98-magerun2 1.1.12 (new formula)

### PR DESCRIPTION
**Pull request by mgeoffray**
Add n98 magerun 2 tools

### CODE REVIEW

**Comment by javian** [comment]
It seems to be failing on the provided test case - can you figure out why ?

**Comment by mgeoffray** [comment]
@javian Where I can see the failing ?    
My local test work well :   
```sh
[matt:...mebrew/homebrew-php/Formula]$ brew audit --strict --online n98-magerun2                                                                    
[matt:...mebrew/homebrew-php/Formula]$   
```
```sh
[matt:...mebrew/homebrew-php/Formula]$ brew install n98-magerun2                                                                                     
==> Installing n98-magerun2 from homebrew/php
==> Downloading https://files.magerun.net/n98-magerun2-1.1.12.phar
######################################################################## 100,0%
🍺  /usr/local/Cellar/n98-magerun2/1.1.12: 4 files, 3.7M, built in 19 seconds
```
```sh
[matt:...mebrew/homebrew-php/Formula]$ la /usr/local/bin | grep n98-magerun2                                                                         
lrwxr-xr-x  1 matt  admin    45B 30 mai 21:57 n98magerun2 -> ../Cellar/n98-magerun2/1.1.12/bin/n98magerun2
```

**Comment by mgeoffray** [comment]
Oh yes OK I see, the file is registered onto `n98magerun2` not `n98-magerun2` like my test

**Comment by mgeoffray** [comment]
@javian Is that possible to specify a name to the output for `def phar_file` ?   
Do I have to use 
```ruby
def install
    bin.install "n98-magerun2-#{version}.phar" => "n98-magerun2"
end
```

**Comment by mgeoffray** [comment]
@javian I have just fix the file that was the output filename

**Pull request closed without merging**
