### PR TITLE
Pinba 1.1.0-dev.7e7cd25

### PR DESCRIPTION
**Pull request by hyperius**

### CODE REVIEW

**Comment by javian** [comment]
You do not have to update the bottle section since the brewbot will do that for you. Just leave it as it is and update the url and sha256 line it and it will be fine.

**Comment by hyperius** [comment]
I've removed it first, then looked on other pull requests and returned it back without any changes.

**Comment by ablyler** [comment]
@hyperius any chance we can get a release with a version from upstream?

**Comment by hyperius** [comment]
Unfortunately there aren't any versioning for extension at now: just master branch and commits in it.

I will contact the author about this, but don't think that issue will be resolved quickly.

**Comment by hyperius** [comment]
@ablyler I've added package version

**Comment by hyperius** [comment]
@ablyler ping ^)

Could you merge or do something with this PR, please?

**Comment by javian** [comment]
I'll see what I can do.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Merged

**Pull request closed without merging**
