### PR TITLE
Introduced php71-igbinary formula

### PR DESCRIPTION
**Pull request by acim**
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
The code seems fine but something has happeend when you were working on it. Can you try and fix the issue ?

**Comment by danijelk** [comment]
Any ETA on this?

**Comment by acim** [comment]
Something broke here, so it would be faster to make new PR.

**Comment by acim** [comment]
New PR is here:

https://github.com/Homebrew/homebrew-php/pull/3853

**Comment by javian** [comment]
If you look at your commit history it includes a merge line which shouldn't be there so I'm assuming that is the issue.

**Comment by acim** [comment]
Yes, I know that, but after the first commit I merged back upstream and in the pull request is just one file involved, but still the two from the first commit were included in the patch. Never mind :)

**Comment by javian** [comment]
The thing is that its not about the file but the git history of it and it needs to add up.

**Comment by acim** [comment]
Then I shall not fork the project but just clone it and send PR straight from my repo?

**Comment by javian** [comment]
The way I do it is forking the project and then adding a new remote in my homebrew directory so I can easily push stuff to my own repo and then submit a PR and easily test changes.

**Comment by acim** [comment]
I did exactly the same and everything went fine with the first commit and PR, but the next one somehow included the previous commit even though it was already merged. Do you make a new fork each time or not? We will se what happens next time. I will try to fix the redis formula next week because we need it anyway.

**Comment by javian** [comment]
As far as I can tell it seems that the changes towards master was merged rather then the branch being rebased towards master but I can't tell you how that happened.

**Comment by acim** [comment]
I didn't rebase, so this is probably the problem. I will do it next time, thanks 😊

**Pull request closed without merging**
