### PR TITLE
Add formula for phive

### PR DESCRIPTION
**Pull request by tommy-muehle**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by tommy-muehle** [comment]
Can anybody give me a hint, if i can fix the build to run the checks successfully?

**Comment by javian** [comment]
@tommy-muehle that was a CI issue so I should be able to deal with it.

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@tommy-muehle Thanks for the submission !

**Pull request closed without merging**
