### PR TITLE
Add php70-xmldiff formula

### PR DESCRIPTION
**Pull request by kfirarad**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Do you know if this also works for php71 ?

**Comment by kfirarad** [comment]
I haven't tried.. using 7.0

**Comment by javian** [comment]
Thanks @kfirarad !

**Comment by kfirarad** [comment]
Thanks for merging @javian

**Pull request closed without merging**
