### PR TITLE
Update php-code-sniffer to 2.1.0

### PR DESCRIPTION
**Pull request by creativecoder**
v2 is now marked stable, so I removed the 'devel' option, as well.

### CODE REVIEW

**Comment by mbrevda** [comment]
dup of #1504

**Comment by tristanbes** [comment]
+1

**Comment by woecifaun** [comment]
:+1:

**Comment by nervo** [comment]
:+1:

**Comment by peterjmit** [comment]
:+1: can we get one of these merged please!

**Comment by alanthing** [comment]
I used #1504 because it refactored the formula to account for the new code no longer being alpha.

**Comment by creativecoder** [comment]
Sounds good--thanks for getting this updated!

**Comment by alanthing** [comment]
You're welcome, thanks for the contribution!

**Pull request closed without merging**
