### PR TITLE
Add formula for Robo

### PR DESCRIPTION
**Pull request by mauricios**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----
Add Robo formula.

Robo is a modern and simple PHP task runner inspired by Gulp and Rake aimed to automate common tasks:

- Writing cross-platform scripts
- Processing assets (less, sass, minification)
- Running tests
- Executing daemons (and workers)
- Watching filesystem changes
- Deployment with sftp/ssh/docker

See: http://robo.li/ and https://github.com/consolidation/Robo

### CODE REVIEW

**Comment by josegonzalez** [comment]
@javian still :-1: on having any new phars added to the homebrew-php repo.

**Comment by javian** [comment]
@mauricios you gotta keep up, 1.0.5 is out =)

**Comment by josegonzalez** [comment]
Pretty much exactly why I didn't want phars in the repo :P

**Comment by mauricios** [comment]
@javian thanks for the heads up, formula updated to robo version 1.0.5

**Comment by javian** [comment]
@mauricios can you rebase and push this again ?

**Pull request closed without merging**
