### PR TITLE
php71-gearman 2.0.1 (new formula)

### LINKED ISSUE #3861: ptheads and gearman for PHP 7.1
Please add them..(

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes #3861.

### CODE REVIEW

**Comment by javian** [comment]
There was a different submission for gearman in #3814 which indicates that there's an upstream issue that's unresolved.

**Comment by alcaeus** [comment]
Oh, you're right. I've reverted the change in `php70-gearman` and added `php71-gearman` in the old 2.0.1 version until the upstream issue is resolved.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @alcaeus !

**Pull request closed without merging**
