### PR TITLE
php71-pthreads 3.1.6 (new formula)

### LINKED ISSUE #3861: ptheads and gearman for PHP 7.1
Please add them..(

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes #3861.

### CODE REVIEW

**Comment by alcaeus** [comment]
@javian I'll have to investigate the build failures, just a quick question about these errors:
> Error: 2 problems in 1 formula
> homebrew/php/php71-pthreads:
>   * macOS has been 64-bit only since 10.6 so 32-bit options are deprecated.
>   * macOS has been 64-bit only since 10.6 so 32-bit options are deprecated.

What's this all about?

**Comment by javian** [comment]
@alcaeus currently I have no clue. Let me ask the others.

**Comment by alcaeus** [comment]
Thanks!

**Comment by javian** [comment]
@ilovezfs would you have a clue as to why it complains about 32bit ?

**Comment by MikeMcQuaid** [comment]
@javian @ilovezfs  Bug on my end. Will fix and rerun the job shortly.

**Comment by MikeMcQuaid** [comment]
@javian Fixed in https://github.com/Homebrew/brew/commit/8f85eb64c4875fed514150dec755cb267a96df74 and requeued job.

**Comment by javian** [comment]
@alcaeus this looks like an upstream issue. There's been developments in the master branch but no release since early this year.

**Comment by alcaeus** [comment]
@javian https://github.com/krakjoe/pthreads/issues/646 indicates you are correct. I'll close this and revisit it once there's an update for pthreads.

**Comment by alcaeus** [comment]
@javian: PHP 7.1 support is still somewhat in the works. The master branch works on PHP 7.1, but a stable release is a little bit away according to the maintainer. I'd refrain from creating a head-only formula for PHP 7.1, what do you think?

**Comment by javian** [comment]
@alcaeus I agree - lets wait with publishing a formula until there is a release to release.

**Pull request closed without merging**
