### PR TITLE
Updated PHP 7.1 from RC6 to stable 7.1.0

### PR DESCRIPTION
**Pull request by devjack**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

This patch updates the PHP 7.1 formula to 7.1.0 (replacing the previous 7.1RC6).

Updated formulae for PHP71 stable release.
Local installs run smoothly (excl. missing bottles prompting source install).

```
$ brew tap homebrew/homebrew-php <fork url>
$ brew install php71
$ php --version
PHP 7.1.0 (cli) (built: Dec  2 2016 15:36:22) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
```

### CODE REVIEW

**Comment by alcaeus** [comment]
IIRC you also need to increase the revision number in the php71.rb formula to trigger a rebuild of the bottles.

**Comment by javian** [comment]
Yes that's correct. Can you make the update @devjack ?

**Comment by devjack** [comment]
Thanks @alcaeus, thats the step I missed.
@javian Updated the revision in 86258ab.
Cheers!

**Comment by freekmurze** [comment]
Thanks for all the work you out into this. Can't wait to upgrade my dev environment. Any ETA when this will be pulled in?

**Comment by bbashy** [comment]
Eager to have this too! :+1:

Thanks.

**Comment by devjack** [comment]
I'm having some trouble understanding whats missing to cleanup the `.h` files after build (causing audit to fail). Happy to do the work to get this merged if anyone can offer some pointers?

**Comment by javian** [comment]
@devjack We've been leaving it like that for now. We could remove the include but I don't know if someone is currently depending on it. Potentially we could make i optional so it doesn't break the CI.

**Comment by javian** [comment]
Thanks for the submission @devjack !

**Pull request closed without merging**
