### PR TITLE
php71-http: Add pecl_http for 7.1 (new formula)

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
I think you messed up this PR, can you please clean it up and keep it to one formula only ? Thanks!

**Comment by SMillerDev** [comment]
will do

**Comment by SMillerDev** [comment]
@javian still something wrong with this one?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@SMillerDev no - its just the notoriety of the github repo that's failing

**Comment by SMillerDev** [comment]
Just noticed this had the same issue as #4290 so fixed that

**Comment by javian** [comment]
THanks @SMillerDev !

**Pull request closed without merging**
