### PR TITLE
Update imagick formulae

### LINKED ISSUE #3916: PHP56-imagick appears to be broken
## Description

PHP56-imagick appears to be broken.
After update imagick to imagemagick-7.0.4-4

Same issue https://github.com/Homebrew/homebrew-php/issues/3912

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.2 (16C68)
**Homebrew Version:**   | 1.1.7
**PHP Version in use:** | 5.6.29
**Xcode Version:**      | _your Xcode version_

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php56-imagick/imagick.so' - dlopen(/usr/local/opt/php56-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.3.dylib
  Referenced from: /usr/local/opt/php56-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 5.6.29 (cli) (built: Dec  9 2016 07:03:56) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Build logs:** _Link to public gist created with `brew gist-logs my-formula`_

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

This should fix #3916, #3912 and takes care of the issue mentioned in #3919:

* php53-imagick is left at version 3.3.0 and instead requires imagemagick@6, since imagick 3.4.0 requires PHP 5.4 or newer.
* php5{4-6}-imagick are updated to 3.4.2 and can use imagemagick 7
* php70-imagick gets a revision bump for good measure
* php71-imagick is updated to 3.4.3-RC2

Edit: Whoops, only now saw #3913. My apologies @javian, feel free to close this if you'd rather finish up your PR.

### CODE REVIEW

**Comment by Danack** [comment]
> since imagick 3.4.0 requires PHP 5.4 or newer.

Just to try to clarify - Imagick still works against [PHP 5.3](https://travis-ci.org/mkoppanen/imagick) - it just isn't supported. 

As in, any bug reports that people try to raise against Imagick that only occur in PHP 5.3 are very unlikely to be investigated or fixed.

**Comment by alcaeus** [comment]
@Danack thanks for the clarification. I also didn't want to invest lots of time getting imagick to run in PHP 5.3, since I'm just waiting for #3689 to be merged.

**Comment by javian** [comment]
@alcaeus lets keep yours since you added the additional code - that's fine with me. Thanks for putting this together!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by holtkamp** [comment]
FYI, Imagick 3.4.3 stable has been released: https://github.com/mkoppanen/imagick/releases/tag/3.4.3

**Comment by javian** [comment]
@holtkamp feel free to submit a PR when you notice such things - thanks! ^^

**Pull request closed without merging**
