### PR TITLE
update swoole to 1.8.11-stable

### PR DESCRIPTION
**Pull request by CarloQ**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
This seems to be failing since the bottles have not been updated. This needs to happen before this can pass.

**Comment by CarloQ** [comment]
Because of the path of sed in phpize, but I don't know how to fix it

**Comment by javian** [comment]
I've submitted bottle updates for 53-55 for now and 56 is ready to be merged so it should be ok soon.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@CarloQ for the record you do not have to manipulate the bottle block, the brewbot will take care of that automatically. We can merge it this time but you can save some time on the next PR if you ignore it =) Thanks for the submission !

**Comment by CarloQ** [comment]
I see~

**Pull request closed without merging**
