### PR TITLE
php72 7.2.0alpha2

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus !

**Comment by bendavies** [comment]
@alcaeus after installing this and apcu, i get
```
php -v
PHP Warning:  PHP Startup: apcu: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20160731
These options need to match
 in Unknown on line 0

Warning: PHP Startup: apcu: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20160731
These options need to match
 in Unknown on line 0
PHP 7.2.0alpha2 (cli) (built: Jun 23 2017 06:46:18) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0alpha2, Copyright (c) 1999-2017, by Zend Technologies
```

any ideas?

**Comment by alcaeus** [comment]
Reinstalling from source (`brew reinstall -s php72-apcu`) fixed the problem. I've created #4309 to recreate the bottles, that should fix it.

**Comment by bendavies** [comment]
@alcaeus thanks!

**Pull request closed without merging**
