### PR TITLE
Adds formula for timecop

### PR DESCRIPTION
**Pull request by keitap**
php-timecop is an extension providing "time travel" capabilities inspired by ruby timecop gem.
ref: https://github.com/hnw/php-timecop

### CODE REVIEW

**Comment by keitap** [comment]
The build has failed because it unfortunately reached GitHub API rate limit.

```
==> brew audit homebrew/php/php53-timecop --strict --online
==> Installing or updating 'rubocop' gem
Successfully installed rainbow-2.1.0
Successfully installed ast-2.2.0
Successfully installed parser-2.3.1.0
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.0
Successfully installed unicode-display_width-1.0.5
Successfully installed rubocop-0.39.0
7 gems installed
Error: GitHub API Error: API rate limit exceeded for 208.78.110.199. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 56 minutes 15 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
```

**Comment by javian** [comment]
Yes this is a known problem without a fix currently. I'll try to rerun the build manually.

**Comment by keitap** [comment]
@javian Is there anything else I need to get this merged? or is it just usual that it takes a couple of weeks to get merged?

**Comment by javian** [comment]
@keitap No it should not take this long. I was working on fixing the build in Travis and get around the issue posted above. I'm retrying again now but I won't be able to take a closer look until tonight.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks for the contribution @keitap ! Sorry that it took a bit of time.

**Comment by keitap** [comment]
@javian Thank you!

**Pull request closed without merging**
