### PR TITLE
php71-7.1.6 (built-in formulae)

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

See #4229.

### CODE REVIEW

**Comment by koreymacdougall** [comment]
Is there a way to use this formula before it is rolled into homebrew/core?
I have run `brew tap alcaeus/homebrew-php --full` but I am unable to upgrade to 7.1.6 through `brew upgrade`.  Also,`brew install php-7.1.6` and similar syntax doesn't work.  I tried making the same modifications in the 10 files listed in this commit, then running `brew update` and `brew upgrade` and that didn't seem to work either.  

I'm new to homebrew and can't find the solution to this in docs or online.  I need to update our server for security reasons, so any help would be much appreciated.

**Comment by alcaeus** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @alcaeus !

**Comment by javian** [comment]
@koreymacdougall generally you would wait until its merged into the official tap. You should be able to apply the PR to test it by doing `brew pull <url to PR>` but I'm not sure if you need to be in home-brew dev mode for that to work.

**Comment by koreymacdougall** [comment]
@javian  thanks for the tip.  I'll keep this in mind for the future.

**Pull request closed without merging**
