### PR TITLE
php56-ioncubeloader 10.0.2

### PR DESCRIPTION
**Pull request by lukebussey**
updated ionCube loaders to latest released version 10.0.2 per ionCube site

- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks! 
Can you also add this change for php70-ioncubeloader and php71-ioncubeloader? That way we have all of them up to date again. 😄

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
One more thing, can you change it to use HTTPS?

**Comment by lukebussey** [comment]
All set. Also updated to 10.0.3.

**Comment by SMillerDev** [comment]
okay, one more thing. 5.3 formulas don't behave well with High Sierra. And it's a very old version anyway. Might as well drop the 5.3 bump since the build is failing on it.

**Comment by lukebussey** [comment]
The issue is Ioncube don't make the previous versions of the loader available via https://www.ioncube.com/loaders.php Anytime they release a version it'll break this formula, so not sure what to do here.

**Comment by javian** [comment]
@lukebussey remove the 5.3 version for now and we can see how we are going to move forward with that since we've talking about completely removing the old php versions.

**Comment by lukebussey** [comment]
OK, i've reverted the 5.4 version.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @lukebussey !

**Pull request closed without merging**
