### PR TITLE
php56 5.6.31

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by alcaeus** [comment]
@javian any chance to get this merged?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by alcaeus** [comment]
@javian is there anything I can do to keep these from failing?

**Comment by javian** [comment]
@alcaeus as far as I know, no. The issue is that one or more of the modules require thread safety and once an extension is compiled with threadsafety its no longer compatible with the non thread safe php binary which we bottle. Until we change how the php formula works this will remain unless we ditch the thread safe extension.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @alcaeus !

**Pull request closed without merging**
