### PR TITLE
php70 7.0.14

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus ! I'll get this merged asap - also releasing 5.6.29 today so the queue is a bit longer than usual =)

**Comment by alcaeus** [comment]
@javian no worries, thanks! 🍻

**Comment by javian** [comment]
We need to address all these brewbot problems some day to make it easier to determine if we have any issues with the build =)

**Comment by alcaeus** [comment]
@javian yes, so I've noticed. BTW, I just wanted to push the revision updates for the core extensions since I forgot those in the first go. Do you want me to create a new PR or do you want to fix them directly?

**Comment by javian** [comment]
@alcaeus Thanks for offering. I was thinking that we perhaps should include the core extensions in the commit when we upgrade the version to include everything in one go. I think I have experimented with that in the past and its very much up to the load on the brewbot if it works or not since it extends the time it takes to produce the bottles but I think I would prefer that to make it a little bit more easy to manage. What do you think ?

**Comment by alcaeus** [comment]
I agree, it should be in one commit. The build architecture should be made to deal with it. After all, updating the core extensions is part of updating the php formula, without it the commit is technically broken.

**Pull request closed without merging**
