### PR TITLE
Add formula for `php70-gearman`

### PR DESCRIPTION
**Pull request by stephenorr**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

This uses the GitHub release of wcgallego/pecl-gearman, in its recently released 2.0.1 stable version, which seems to work fine with PHP 7 (please note, it doesn't work with older versions of PHP; only with 7.0 onwards).

PECL itself seems to be largely dead these days, so this is one of the easier ways for mere mortals to get these packages installed and running. I've tested this on my local dev system running El Capitan, and I'll also try it on Sierra when I get home.
-----

### CODE REVIEW

**Comment by javian** [comment]
It won't pass until the forked repo status is removed from the one that is used now. I've posted a request to do that here https://github.com/wcgallego/pecl-gearman/issues/33

**Comment by javian** [comment]
But I will merge it for now since the rest passes so its mainly an annoyance.

**Comment by javian** [comment]
Thanks for the submission @stephenorr ! Glad we made it here in the end =)

**Comment by stephenorr** [comment]
Me too @javian - and it was my pleasure to help :)

**Pull request closed without merging**
