### PR TITLE
adminer 4.4.0

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by SMillerDev** [comment]
Fails because the homepage is down. Developer seems to be @vrana maybe they can tell us about that?

**Comment by vrana** [comment]
The homepage is not down, it's just very slow to respond.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @vrana !

**Pull request closed without merging**
