### PR TITLE
Add php-xdiff extension for all versions

### PR DESCRIPTION
**Pull request by jjeising**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Even with the removal of older versions the extension move to a graveyard, too.

### CODE REVIEW

**Comment by jjeising** [comment]
Any progress or further interest here?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
So, the php5.3 extension fails on the new macOS version. If you don't really need it you might as well drop the old php versions.

**Comment by jjeising** [comment]
What fails is the dependency build of `php53`. It happens because of a missing dependency on build time:
```
configure: error: bison is required to build PHP/Zend when building a GIT checkout!
```
But I can probably remove the `php53-xdiff` file from the commit if this helps?

**Comment by SMillerDev** [comment]
That's the easy solution as it's a far outdated PHP version anyway.

**Comment by jjeising** [comment]
Dropped `php53-xdiff`.

**Comment by SMillerDev** [comment]
Thanks @jjeising

**Pull request closed without merging**
