### PR TITLE
phpcpd 4.0.0

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by SMillerDev** [comment]
There seem to be errors for Sierra only. Wonderful... Any comments on this @javian ?

**Comment by javian** [comment]
It seems to require php 7.1 and up now see https://github.com/sebastianbergmann/phpcpd/blob/master/composer.json#L25 and the older versions of macOS doesn't use that.

**Comment by javian** [comment]
That said we can merge this with the same caveat as with phpunit, people would have to figure out to install the right version.

**Comment by javian** [comment]
Thanks @BePsvPT !

**Pull request closed without merging**
