### PR TITLE
gRPC: Update to version 1.1.0 and add formula for PHP 7.0 and 7.1

### PR DESCRIPTION
**Pull request by stanley-cheung**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Hi @stanley-cheung I can't currently accept these formulas and will be removing grpc from the php tap this weekend since its currently breaking our CI and bottling process due to grpc being an external Formula. If you can get grpc into core then we can revisit this.

**Comment by stanley-cheung** [comment]
Hi @javian, can you please clarify what do you mean by "external Formula"? This should be a standalone formula that does not depend on anything (I did just remove a `depends_on` clause from this formula.

This should just build our gRPC Pecl extension and has no dependency. Is that OK for this tap?

**Comment by javian** [comment]
What I meant was that grpc as a dependency is external to the homebrew project since its hosted on the grpc site. If its possible to remove it and its not a requirement to make it compile then that would work as well.

**Comment by stanley-cheung** [comment]
Yes then this PR actually removes that dependency. It's not a requirement to `depends_on` the external `grpc/homebrew-grpc` repo anymore.

Thanks

**Comment by javian** [comment]
@stanley-cheung can you also fix the php5* formulas for that dependency as well ?

**Comment by javian** [comment]
@stanley-cheung and you don't have to remove the bottle code - the bot will take care of that by itself.

**Comment by stanley-cheung** [comment]
@javian Yep already did remove the dependency from the php5* formulas in this PR.

**Comment by javian** [comment]
@stanley-cheung thanks. I must have been confused not seeing that at the time. I will merge this now.

**Comment by stanley-cheung** [comment]
Thanks!

**Pull request closed without merging**
