### PR TITLE
php-cs-fixer 2.0.0

### PR DESCRIPTION
**Pull request by BePsvPT**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by BePsvPT** [comment]
@javian The CI build failed, I don't know how to fix it.

**Comment by alcaeus** [comment]
The error message is:
> fully scope test system calls e.g. system "#{bin}/php-cs-fixer"

This affects the test block in lines 28-30.

**Comment by javian** [comment]
Yes, it want's you to be explicit about the path to the binary that's executed by `system`. Does it make sense to you @BePsvPT ?

**Comment by BePsvPT** [comment]
@alcaeus  @javian thanks, it passed.

**Comment by javian** [comment]
Thanks for the submission @BePsvPT !

**Pull request closed without merging**
