### PR TITLE
php72 7.2.0RC3

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Supersedes #4446.

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by alcaeus** [comment]
@SMillerDev fixed audit errors due to HTTP URLs for `homepage`. Should I drop the `version` field from the extensions as well?
> Stable: version 7.2.0RC2 is redundant with version scanned from URL

**Comment by javian** [comment]
@alcaeus please remove the version as well thanks!

**Comment by alcaeus** [comment]
@javian Done!

**Comment by morloderex** [comment]
please merge this! @javian

**Comment by moderndeveloperllc** [comment]
@javian @alcaeus Looks like just when this is ready to go, @remicollet has tagged and built RC3 - https://downloads.php.net/~remi/

**Comment by alcaeus** [comment]
@moderndeveloperllc It will be announced on the 28th - I think we might as well hold this back until then and go directly to RC3.

**Comment by SMillerDev** [comment]
@alcaeus there already seems to be RC3 files. Might as well upgrade now I guess

**Comment by alcaeus** [comment]
@SMillerDev good point. Done.

**Comment by SMillerDev** [comment]
Do module version issues follow you around all the time or is this purely coincedental @alcaeus ? :smile:

**Comment by alcaeus** [comment]
Oh. Come. On. FWIW, that was the reason you had the "pleasure" of merging tons of revision bumps. Not sure why everything is failing again, but looks like I have to redo it all over again :|

This time however, I'd like to take a look at why those php72 bottles keep being recompiled against an old API version.

**Comment by SMillerDev** [comment]
From what I can see these are just bumps you missed, most of them are from June 29th. Since nothing in the formula actually changed you can use `rebuild 1` in the bottle block btw. (just found that in the 1.3 changelog)

**Comment by SMillerDev** [comment]
Merging #4308 will fix at least one of these issues.

**Comment by alcaeus** [comment]
> From what I can see these are just bumps you missed, most of them are from June 29th.

Interesting - I originally installed all extensions and grepped out the API failures to only update those. Weird.

I'll create the pull requests over the next few hours to not overload the build system like last time.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Just to clarify, do not use rebuild in the bottle blocks. You should continue to bump the revision value or add it to "refresh" a bottle.

**Comment by jonnybarnes** [comment]
Anyone know what’s holding this up?

**Comment by alcaeus** [comment]
@jonnybarnes lots of build failures in dependent formulas - I'll have to take a look at those and decide which ones can be ignored (which most likely won't be many) and which need to be fixed. We don't want broken stuff to end up in a tap, do we? :)

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by alcaeus** [comment]
@javian I can take a look at imagick and libsodium today - not sure what's causing the issues. The rest of the build failures look like they are caused by those two extensions.

**Comment by moderndeveloperllc** [comment]
@alcaeus Just an FYI on `libsodium`, it was recently update to 1.0.15 that has `libsodium.23.dylib`, but I don't know if the PHP build scripts are looking for that version yet.

**Comment by alcaeus** [comment]
@moderndeveloperllc thanks for the hint, I'll check that. I couldn't find a problem with `imagick` locally, no idea what's causing that.

**Comment by jonnybarnes** [comment]
Yeah, when I updated libsodium I started getting errors with php not finding the correct file.

Re-installing `php72-libsodium` with `--build-from-source` got that working again.

**Comment by SMillerDev** [comment]
RC4 available online @alcaeus

**Comment by remicollet** [comment]
@SMillerDev notice than until officially announced 7.2.0RC4 is not yet officially available ;)

**Comment by SMillerDev** [comment]
@remicollet I'm just so excited 😄

**Comment by alcaeus** [comment]
@remicollet @SMillerDev I'll update the formula tomorrow, but assuming some extensions still fail I'll most likely need a few more days to solve this. Any help is greatly appreciated as I've got no clue how to fix it and I also couldn't reproduce it locally.

**Comment by SMillerDev** [comment]
@alcaeus #4511 might fix at least one of them

**Comment by javian** [comment]
Thanks @alcaeus ! We'll see if we can get the extensions to work now.

**Pull request closed without merging**
