### PR TITLE
php71-ref (new formula)

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

This PR adds formula for [php-ref](https://github.com/pinepain/php-ref) PHP extension that adds soft and weak references to PHP (PHP 7 only). 

Disclaimer: I am the author of this php extension.

### CODE REVIEW

**Comment by pinepain** [comment]
The reason of failure is `GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)`.

**Comment by javian** [comment]
You seem to have chosen the same name as https://github.com/digitalnature/php-ref but since that's not an extension I don't think it will be a problem.

**Comment by javian** [comment]
Thanks for the submission @pinepain - its now been merged.

**Comment by pinepain** [comment]
I didn't even supposed that they exists until now. Hope there will be no confusion and https://github.com/digitalnature/php-ref won't mind such naming.

Originally php-ref was named php-weak (which was a php 7 impl. of https://github.com/colder/php-weakref with minor tweaks, before they added php7 support), but after soft refs was added recently, I had to come with a better naming, so `ref` is for **Ref**erence (basically, root namespace in this  ext is `Ref`) like java.lang.ref, but for PHP.

**Pull request closed without merging**
