### PR TITLE
update for macOS Sierra

### PR DESCRIPTION
**Pull request by adashyan**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

PHP API version in macOS Sierra is "20131106"

### CODE REVIEW

**Comment by adashyan** [comment]
PHP API version in macOS Sierra is "20131106"

**Comment by adashyan** [comment]
PHP API version in macOS Sierra is "20131106"

**Comment by adashyan** [comment]
PHP API version in macOS Sierra is "20131106"

**Comment by adashyan** [comment]
PHP API version in macOS Sierra is "20131106"

**Comment by adashyan** [comment]
PHP API version in macOS Sierra is "20131106"

**Comment by javian** [comment]
@adashyan thanks for the submission!

**Pull request closed without merging**
