### PR TITLE
Blitz 0.9.1

### PR DESCRIPTION
**Pull request by WouterDS**

### CODE REVIEW

**Comment by alanthing** [comment]
Can you run `brew audit --strict path/to/formula.rb` on each of the 4 files, follow the remediation steps, and update your PR? Thanks.

**Comment by WouterDS** [comment]
@alanthing: I'll check

**Comment by WouterDS** [comment]
Huh..

@BrewTestBot: Can you test again?

**Comment by WouterDS** [comment]
@alanthing why does it not work? Brew audit says everything is ok?

**Comment by ablyler** [comment]
@BrewTestBot please test again.

**Comment by ablyler** [comment]
I fixed up the changes and merged them.  Thanks!

**Pull request closed without merging**
