### PR TITLE
Boneyard phpsh

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

As per https://github.com/Homebrew/homebrew-php/issues/3868#issuecomment-268902025. Note, this will conflict with #3815 since both add a `tap_migrations` file.

Goes together with https://github.com/Homebrew/homebrew-boneyard/pull/261.

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus - I'll check what's up with the boneyard repo since the last PR wasn't accepted.

**Comment by javian** [comment]
@alcaeus were you aware of this ? https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/boneyard-formula-pr.rb I just found out.

**Comment by alcaeus** [comment]
Huh...I'll have to check out the dev tools. I never saw that tool.

**Comment by javian** [comment]
Thanks @alcaeus this has now been merged.

**Pull request closed without merging**
