### PR TITLE
igbinary 2.0.5 for php5x dependencies

### PR DESCRIPTION
**Pull request by BePsvPT**
separated from #4566

### CODE REVIEW

**Comment by javian** [comment]
hmm still timing out, can you limit it to 5.5 and 5.6 ?

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
After removing 5.4, it finally passed the test. However, I think high sierra takes two times longer than sierra and el capitan is unusual.

**Comment by javian** [comment]
That might just have been temporary, haven't even thought about that before. Will merge this as soon as technically possible.

**Comment by SMillerDev** [comment]
Thanks @BePsvPT !

**Pull request closed without merging**
