### PR TITLE
Boneyard phpenv formula

### LINKED ISSUE #3746: Boneyard phpenv recipe
The [upstream repository](https://github.com/CHH/phpenv) has not been updated in 2 years. While there is an [alternative](https://github.com/phpenv/phpenv), we need to first boneyard the existing one.

What is the usage of our `CHH/phpenv` formula?

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Goes together with Homebrew/homebrew-boneyard#255.

Closes #3746.

### CODE REVIEW

**Comment by javian** [comment]
We should add a migrations reference don't you think ?

**Comment by alcaeus** [comment]
Excellent idea! I've added the phpenv formula to the file. Should I check for other formulae that were moved recently and add them to the list in a separate PR?

**Comment by javian** [comment]
@alcaeus I can't think of any off the top of my head but please do. The last ones we removed were related to tokyotyrant iirc but they were just deleted and not moved anywhere.

**Comment by alcaeus** [comment]
@javian you are correct, a quick look with `git log --diff-filter=D --summary` revealed no files that are worth being added to the migratinos list. Even the tokyotyrant removals are extension formulae, which are not added to the boneyard (at least not until we take care of #3686).

**Comment by javian** [comment]
@alcaeus now that I merged the other boneyarded formula this conflicts with master now - can you rebase and push it again ?

**Comment by alcaeus** [comment]
Done.

**Comment by javian** [comment]
Thanks @alcaeus !

**Pull request closed without merging**
