### PR TITLE
Add formula for drush-launcher

### PR DESCRIPTION
**Pull request by webflo**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Hi, here is a formula for the new drush-launcher. The app is a small phar file, no further configuration needed.

### CODE REVIEW

**Comment by webflo** [comment]
Related to https://github.com/drush-ops/drush-launcher/issues/34

**Comment by SMillerDev** [comment]
The build is failing on an incorrect hash of the file. Can you run `brew reinstall --build-from-source <formula>` to see if it happens locally as well?

**Comment by SMillerDev** [comment]
Still failing, now on the test block

**Comment by webflo** [comment]
Thanks for your feedback. I will fix the bug in drush-launcher itself.

**Comment by webflo** [comment]
I created a new release for drush-launcher and fix the test method in the formular

**Comment by webflo** [comment]
@SMillerDev I think this is ready. Thanks for your help!

**Comment by SMillerDev** [comment]
Thanks @webflo

**Pull request closed without merging**
