### PR TITLE
php{56-71}-ice 3.7.0 (new formula)

### PR DESCRIPTION
**Pull request by externl**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
The naming format should be more along these lines:
`php{56-71}-ice 3.7.0 (new formula)`

**Comment by externl** [comment]
Thanks @SMillerDev. I've updated the commit.

**Comment by externl** [comment]
Anything else required here?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@externl the hashes seem to be changed since this pull request. Could you update them?

**Comment by externl** [comment]
Done.

**Comment by SMillerDev** [comment]
Thanks @externl

**Pull request closed without merging**
