### PR TITLE
codeception 2.3.8

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BePsvPT can you fix the HTTP vs HTTPS references?

**Comment by javian** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
