### PR TITLE
php71-phalcon 3.2.4

### PR DESCRIPTION
**Pull request by Swift-R**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the pull request, it looks good. But can you add changes for 56 and 70 too? Would be a shame if those were still on an older version while an update is available.

**Comment by Swift-R** [comment]
Oh, right... Can I commit to this PR after removing the fork?

**Comment by SMillerDev** [comment]
Don't think so, no :(

**Comment by SMillerDev** [comment]
Seems I can't pull a diff either from a fork that is removed before merging, can't merge this or your other PR unfortunately.

**Pull request closed without merging**
