### PR TITLE
Update (lib)sodium to 2.x for PHP 7.0 and 7.1 and rename to sodium

### PR DESCRIPTION
**Pull request by mdeboer**
As of version 2.0.0 the compatibility layer for PHP < 7.0 has been
removed and the extension has been renamed to just sodium. Also the
namespaces have been removed and the API has been made compatible with
what will be shipped with 7.2. The 1.x branch will not receive any
public updates anymore.

See #4426

### CODE REVIEW

**Comment by mdeboer** [comment]
Hmm, I see libsodium can't be named @1.0 if there's no libsodium package. Is it possible to create an alias for libsodium -> sodium? Otherwise having two packages libsodium (1.0) and sodium (2.0) would be confusing.

**Comment by SMillerDev** [comment]
That's what https://github.com/Homebrew/homebrew-php/blob/master/formula_renames.json is for right?

**Comment by mdeboer** [comment]
Ah, great @SMillerDev thanks. First contribution here 😨  I'll make the changes 👍

**Comment by SMillerDev** [comment]
Never worked with that file either so it's equal parts question and comment :p
Also yay, new contributors

**Comment by mkoppmann** [comment]
There was already an attempt to merge sodium 2.x here #4323. Don’t know exactly why it didn’t got merged, but it would be great, if yours did :)

**Comment by mdeboer** [comment]
@SMillerDev aww shit you got my hopes up there 😋  My first attempt failed by simply keeping the name libsodium and versioning 1.x with @1 but that didn't work. It builds fine but doesn't configure the PHP.ini correctly as it adds libsodium.so instead of sodium.so.

Like I said before, it would be quite confusing I think if we keep both libsodium and sodium without versioning libsodium as @1 but for now, I don't see any other way if `formula_renames.json` doesn't work.

So, I'd be happy to fix this and push a new commit. Except I don't know what to do next.

In the meanwhile if people are looking for a solution to run libsodium 2.x in PHP 7.0-7.1, just run:
`brew install --HEAD php71-libsodium` and then rename `libsodium.so` in  `/usr/local/etc/php/7.1/ext-libsodium.ini` to `sodium.so`. Or as the RC's are starting to come out, you can run PHP 7.2 if you dare.

**Comment by PhilETaylor** [comment]
grrr

```
~ brew install --HEAD php71-libsodium
==> Installing php71-libsodium from homebrew/php
==> Cloning https://github.com/jedisct1/libsodium-php.git
Updating /Users/phil/Library/Caches/Homebrew/php71-libsodium--git
==> Checking out branch master
==> /usr/local/opt/php71/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php71-libsodium/HEAD-993fbd8 --with-p
==> make
Error: No such file or directory - modules/libsodium.so
```

**Comment by mdeboer** [comment]
@PhilETaylor strange, for me it built fine a few weeks ago. Well then it seems that solution went down the drain.

Can someone please point me in the right direction to fix this issue (see my previous post)?

**Comment by PhilETaylor** [comment]
Issue I have now is that all my code on my mac uses 1.0.x functions and on the live server is 2.0.x versions.... grrr ... sunday afternoon fun...

**Comment by SMillerDev** [comment]
So, @mdeboer have you tried using the Aliases directory to make an alias from libsodium to sodium, then this can be libsodium@1.0. You can try installing it locally, and if it works please push (as you're clearly not the only person with this issue)
_Just a late night thought on my end, maybe it'll work. Think it's better than renaming_

**Comment by mdeboer** [comment]
Thanks @SMillerDev, I'll play around with it 👍

**Comment by mdeboer** [comment]
Alright, third time's a charm I hope, fingers crossed! 🤞  

- [x] Added the formulae to `formula_renames.json` (which seems to work)
- [x] Removed deprecated `ENV.universal_binary` according to the audit output
- [x] Renamed the `libsodium.so` files to `libsodiumat10` as that's the name is in the configuration file that's generated. (dirty imho, but working)

Assuming this passes the build/audit tests (as it does locally), next thing to make things clean is to avoid having to rename to `libsodiumat10.so` and changing the configuration file instead to reference `libsodium.so`. Maybe some `write_config_file` trickery that I'm not aware of?

**Comment by mdeboer** [comment]
Okay, so apparently according to the logs the build still fails because it fails to find the extension in `php -m` as I guess it looks for `libsodiumat10` instead of `libsodium`. I wonder how that's handled for extensions like `opcache` which show up like `Zend OPcache` and not as `opcache`. Fixing that should fix the build.

Why did they have to rename this -sigh- 😭 

Log output:
```
==> /usr/local/opt/php71/bin/php -m
Error: homebrew/php/php71-libsodium@1.0: failed
failed to find extension in php -m output
```

**Comment by SMillerDev** [comment]
@BrewTestBot Test this please

**Comment by SMillerDev** [comment]
Thanks @mdeboer

**Comment by mdeboer** [comment]
You're welcome, thanks for the merge! 👍

**Comment by moderndeveloperllc** [comment]
@mdeboer Thanks for doing this the right way. I tried to get a PR for this a few months ago, but didn't know the inner workings of renaming formulas to get the repo owners to merge it.

**Pull request closed without merging**
