### PR TITLE
Add PHP postgresql module

### PR DESCRIPTION
**Pull request by jdecool**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the PR, however what's the benefit over installing php `--with-postgresql`?

**Comment by jdecool** [comment]
It's because in the PHP documentation (https://secure.php.net/manual/en/pgsql.installation.php), it is need to enable `PostgreSQL support`.

**Comment by SMillerDev** [comment]
but we already have https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb#L367 to do that right?

**Comment by jdecool** [comment]
I update this PR

**Comment by kenorb** [comment]
Related: #4720.

**Comment by jdecool** [comment]
@SMillerDev Does it miss something to this PR to be merged ?

**Comment by SMillerDev** [comment]
sorry for the long wait, I'm still not sure what it adds over the default php install `--with-postgresql` tough.

**Comment by jdecool** [comment]
No problem @SMillerDev 

And because i didn't do that before, thanks for your awesome work on this tool.

> Thanks for the PR, however what's the benefit over installing php --with-postgresql?

I just realise that I didn't understand what you mean in your comment.

I didn't know that we can do `brew install php72 --with-postgresql`.

In fact you're right, this PR doesn't add anything. We can close it.

**Pull request closed without merging**
