### PR TITLE
php-timecop 1.2.10

### PR DESCRIPTION
**Pull request by SMillerDev**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
This currently fails and has been reported here https://github.com/hnw/php-timecop/issues/29 so we are awaiting an upstream fix before this can be merged.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Looks like we are seeing a few new errors now.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
