### PR TITLE
Upgrade php71 to 7.1.0 alpha2

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
Why are bottles being deleted?

**Comment by pinepain** [comment]
Because they will be updated with the new proper one by bot later.

**Comment by ilovezfs** [comment]
Yeah, you shouldn't modify the bottle block at all. That's bot's job.

**Comment by pinepain** [comment]
I used this commit as a reference - https://github.com/Homebrew/homebrew-php/commit/42592c392396ef8da8b92fbbeea9954dec44824b which clean bottles. I didn't initially touch php formula, so not sure what is an appropriate way to handle php upgrades. With standalone formula it's clear, but here we introduce changes to parent formula. What is an appropriate way to handle php upgrades?

**Comment by javian** [comment]
Yeah that wasn't handled properly and as @ilovezfs points out we don't need to touch the bottle section in the formula so please revert that change in the PR. Thanks!

**Comment by pinepain** [comment]
Ok, thanks for clarifying.

**Comment by pinepain** [comment]
Fixed.

**Comment by javian** [comment]
Thanks @pinepain !

**Pull request closed without merging**
