### PR TITLE
Add formulas for new mongodb driver

### PR DESCRIPTION
**Pull request by alcaeus**
* Add formula for new mongo-php-driver for PHP 5.4, 5.5, 5.6

Note: as mentioned in https://github.com/Homebrew/homebrew-php/pull/2533#issuecomment-159392038, there is no support for PHP 7 yet. Once this is done the corresponding formula may be added.

### CODE REVIEW

**Comment by ablyler** [comment]
@alcaeus can you add a desc to each of these formulas? `brew audit --strict` complains about this: http://bot.brew.sh/job/Homebrew%20PHP%20Pull%20Requests/1122/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/audit_homebrew_php_php56_mongodb___strict___online/

**Comment by alcaeus** [comment]
Whoops, my bad. I've gone ahead and added them to the legacy driver as well.

**Comment by alcaeus** [comment]
Not quite sure what's going on with 10.11, had a similar issue on my machine. Had to ```brew link openssl --force``` to get it to compile, is there something I'm missing?

**Comment by ablyler** [comment]
@mikemcquaid any ideas on the openssl issue? ^

**Comment by mikemcquaid** [comment]
> Had to brew link openssl --force to get it to compile, is there something I'm missing?

This is never a good idea, FWIW, as you may well link against an old, insecure version.

> @mikemcquaid any ideas on the openssl issue? ^

At the least it'll need a `depends_on "openssl"`. It may also need `./configure` and/or `CFLAGS` set too.

**Comment by alcaeus** [comment]
I'll see if I can fix it, thanks for the info!

**Comment by ablyler** [comment]
@alcaeus i went ahead and fixed up your PR in PR #2546 Thanks!

**Comment by alcaeus** [comment]
Thank you! :beers:

**Pull request closed without merging**
