### PR TITLE
add php56-translit.rb

### PR DESCRIPTION
**Pull request by glensc**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

my first formula, builds locally, be gentle

```
$ brew install --build-from-source php56-translit.rb
==> Downloading https://github.com/derickr/pecl-translit/archive/RELEASE_0_6_2.tar.gz
Already downloaded: /Users/glen/Library/Caches/Homebrew/php56-translit-0.6.2.tar.gz
==> /usr/local/opt/php56/bin/phpize
==> ./configure --prefix=/usr/local/Cellar/php56-translit/0.6.2 --with-php-config=/usr/local/opt/php56/bin/php-config
==> make
==> Caveats
To finish installing translit for PHP 5.6:
  * /usr/local/etc/php/5.6/conf.d/ext-translit.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the translit module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run `php -i "(command-line 'phpinfo()')"`
  * - Look for the info on the translit module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php56-translit/0.6.2: 3 files, 571.2K, built in 11 seconds

$ cat /usr/local/etc/php/5.6/conf.d/ext-translit.ini
[translit]
extension="/usr/local/opt/php56-translit/translit.so"

$ php -m|grep -i translit
translit

```

### CODE REVIEW

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by yurikoles** [comment]
@BrewTestBot test this please

**Comment by glensc** [comment]
what is needed to get this merged?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @glensc !

**Comment by glensc** [comment]
super thanks here :tada:

**Pull request closed without merging**
