### PR TITLE
php72 7.2.0

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Files are already there, but it might be worth waiting for the official announcement for the final release.

### CODE REVIEW

**Comment by radimvaculik** [comment]
PHP 7.2.0 officially released http://php.net/archive/2017.php#id2017-11-30-1

**Comment by SMillerDev** [comment]
@BrewTestBot test this please!

**Comment by SMillerDev** [comment]
@alcaeus shouldn't this include libsodium?

**Comment by alcaeus** [comment]
I’m not sure - I assumed this was already handled during the RC phase. What do you think is missing?

**Comment by SMillerDev** [comment]
I thought it would need a version bump as well. But not so sure anymore now.

**Comment by alcaeus** [comment]
On mobile atm, can check in a moment. I bumped revisions for everything that is built from the PHP tarball.

**Comment by SMillerDev** [comment]
Just checked, I was wrong

**Comment by alcaeus** [comment]
Good to know, thanks for checking. 👍

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
So to get the Sierra builds to work we need to add `ENV["SDKROOT"] = MacOS.sdk_path` on Sierra only which should solve the issue with the linker not finding the system library. @alcaeus can you add that ?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
So the primary fix for Sierra is now merged and I expect a few of the test to fail still but it should compile so we can merge the bottles and formulas for the latest releases.

**Comment by javian** [comment]
Thanks @alcaeus !

**Comment by alcaeus** [comment]
Thanks @javian for taking over!

**Pull request closed without merging**
