### PR TITLE
Add php70-trader extension

### PR DESCRIPTION
**Pull request by oktapodia**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----
Hello

This is my first contribution on brew, I still have a little problem, when I uninstall my php-trader extension, my `/usr/local/etc/php/7.0/conf.d/ext-trader.ini` still in the `conf.d` folder, how can I remove it automatically please?

Regards

### CODE REVIEW

**Comment by javian** [comment]
@oktapodia the config file can't be remove automatically as far as I know and its the same as with all other extensions.

**Comment by alcaeus** [comment]
FWIW, it would make sense to add this formula for the other PHP versions as well.

**Comment by oktapodia** [comment]
@alcaeus Added

**Comment by oktapodia** [comment]
@alcaeus Do you know when will you able to merge it please?

**Comment by alcaeus** [comment]
@oktapodia I won’t merge it because I don’t have write access to this repository. @javian could you take a look?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by irazasyed** [comment]
Any updates on when this will be merged? Been trying to install this extension. Please merge. Thanks!

**Comment by oktapodia** [comment]
I sadly don't know @javian could you take a look, please?

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Could you rename the commits `php53-trader: 0.4.0 (new formula)`?

**Comment by oktapodia** [comment]
@SMillerDev Done

**Comment by SMillerDev** [comment]
I meant all of them (sorry, I was unclear about that)

so all of them in the format `php##-trader: 0.4.0 (new formula)`

**Comment by SMillerDev** [comment]
build for the 5.3 extension is failing, unless you really need them you might as well drop the addition for old php versions

**Comment by oktapodia** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @oktapodia !

**Pull request closed without merging**
