### PR TITLE
php56 5.6.25

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

As per #3502.

This build is known to fail audit because of installing php headers.

### CODE REVIEW

**Comment by pinepain** [comment]
It looks like `php56-tidy` was not built before, bottles block was empty.

**Comment by javian** [comment]
Can you push only the php56.rb and the versions file like #3509 ?
For Tidy we have to rebuild the bottle against the new version anyway so that will sort itself out I think.

**Comment by pinepain** [comment]
Done.

**Comment by javian** [comment]
Can you please also remove the code inside the bottle code here - something is up with the double revision statement.

**Comment by pinepain** [comment]
Bottle block cleaned.

**Comment by pinepain** [comment]
Red build again and even more fancier error in log, e.g.:

```
Testing homebrew/php/php56-gearman
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160821-59597-t9pmce.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-php/Formula/php56-gearman.rb --verbose
==> /usr/local/opt/php56/bin/php -m
PHP Fatal error:  Function annotation compilation failed for function cbdsn_stringify in file [CouchbaseNative]/connstr.php at line 193, error message: You MUST specify a type for all parameters
 in Unknown on line 0
Error: homebrew/php/php56-gearman: failed
```

**Pull request closed without merging**
