### PR TITLE
php71: migrate to homebrew/core

### PR DESCRIPTION
**Pull request by kabel**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?

-----

Depends on https://github.com/Homebrew/homebrew-core/pull/24766

### CODE REVIEW

**Comment by javian** [comment]
@brewtestbot test this please

**Comment by SMillerDev** [comment]
@kabel it seems there are a couple of formulae with hardcoded php71 dependencies. Would you mind checking these?

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/infection.rb
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Formula/xdebug-osx.rb
No available formula with the name "php71" 
No available formula with the name "php71"

**Comment by kabel** [comment]
Will do. Had it locally but didn't commit/push

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@kabel can you rebase once more?

**Comment by ilovezfs** [comment]
Thanks @kabel!

**Comment by kabel** [comment]
After you `brew install php@7.1` those extensions are already included. See `$(brew --prefix)/opt/php@7.1/bin/php -m`. No need to use any install options or separate formulae.

**Comment by Saeven** [comment]
Damn you beat me to it.  Thanks @kabel, just ran php -i and saw them.

**Comment by orcinus** [comment]
I'm sorry, but this is a complete and utter mess compared to the "old" josegonzales kegs.
Doesn't automatically import into path, no way to pick extensions, and to top it all off, getting this:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-intl/intl.so' - dlopen(/usr/local/opt/php71-intl/intl.so, 9): image not found in Unknown on line 0
```

Which sounds oddly familiar from here:
https://github.com/Homebrew/homebrew-php/issues/4384

Tried brew reinstall, no dice.

**Comment by kabel** [comment]
@orcinus  Migrations tend to be a bit messy. The warning you are receiving are from old configuration files that no longer apply to the migrated formula. Please check your `/usr/local/etc/php/7.1/conf.d/` for extension ini files that aren't automatically removed.

The automatic linking (importing into path) is a feature reserved for the most recent php branch. If you wish to use this version exclusively, you can force the linking with `brew link --force php@7.1`.

**Comment by simPod** [comment]
Where did SNMP extension go?

**Comment by SMillerDev** [comment]
@simPod SNMP was excluded from the build because it crashes Apache.

**Comment by MikeMcQuaid** [comment]
> I'm sorry, but this is a complete and utter mess compared to the "old" josegonzales kegs.

@orcinus Read our [Code of Conduct](https://github.com/Homebrew/homebrew-core/blob/master/CODE_OF_CONDUCT.md) and adjust your future communication accordingly.

**Pull request merged**
