### PR TITLE
Upgrade php 7.0/7.1 to apcu 5.1.8

### PR DESCRIPTION
**Pull request by andig**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/krakjoe/apcu/issues/200

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by ilovezfs** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks for the submission @andig !

**Comment by andig** [comment]
@javian closed with unmerged commits- anything wrong?

**Pull request closed without merging**
