### PR TITLE
Add Climb

### PR DESCRIPTION
**Pull request by vinkla**
A Composer version manager tool https://github.com/vinkla/climb

### CODE REVIEW

**Comment by vinkla** [comment]
It seems Travis is failing, how do I go about fixing it?

**Comment by ablyler** [comment]
@vinkla don't worry about Travis, that is still a work in progress.

**Comment by ablyler** [comment]
@vinkla merged, thanks for the PR!

**Comment by vinkla** [comment]
Awesome! Thank you!

**Pull request closed without merging**
