### PR TITLE
libmustache 0.4.0

### PR DESCRIPTION
**Pull request by ablyler**

### CODE REVIEW

**Comment by ablyler** [comment]
@Homebrew/maintainers for some reason this didn't kick off a brew bot job.

**Comment by DomT4** [comment]
Give it a few minutes...

**Comment by DomT4** [comment]
There you go :wink:. The new Jenkins update is a _touch_ slower than the prior version at queuing the build up apparently. I'll restart CI later to see if it self-resolves but otherwise builds are going to take 4 minutes or so to queue, which isn't the end of the world.

**Comment by ablyler** [comment]
@DomT4 thanks! sorry for not being patient, I just got used to it being queued realtime. :smile:

**Comment by DomT4** [comment]
Just bear in mind when you use the maintainers tag we all get a notification and most of us get an email :smile:. If it doesn't appear on the queue after 10 minutes or so feel free to ping one of us at that point and we'll take a look. I suspect the slower queuing is a temporary issue, personally.

**Comment by ablyler** [comment]
@DomT4 no worries, is there a mailing list where these types of changes are announced? i would love to be kept in the loop when changes like this happen, so that I don't ping you guys unnecessarily.

**Comment by DomT4** [comment]
Essentially any time `jenkins-lts` is updated in `homebrew/versions` the CI will be updated within a few hours of that.

**Pull request closed without merging**
