### PR TITLE
Upgrade imagick 3.1.2 and Add configure parameter --with-imagick

### PR DESCRIPTION
**Pull request by n0ts**
Hi, imagick pecl stable version is 3.1.2, so I upgrade imagick 3.1.0RC2 to 3.1.2.
http://pecl.php.net/package/imagick

And I got a bellow error, so I add --with-imagick configure parameter.

```
checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
```

Thanks.

### CODE REVIEW

**Comment by alanthing** [comment]
Thanks!

Curious, as I haven't test it yet: is the in-line patch still necessary? Could you test removing it on your local machine and see if the module still builds and works as expected without it? No big deal if we still need it, but between the older RC version we had and the version you bumped it up to, that issue might have been fixed.

**Comment by n0ts** [comment]
@alanthing 
Hi, Thanks comment.
Yes, in-line patch still necessary.

```
...
checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
```

**Comment by alanthing** [comment]
@BrewTestBot test this please

**Comment by n0ts** [comment]
:+1:

**Pull request closed without merging**
