### PR TITLE
php70-gmp 7.0.19

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
php 8 ? =)

**Comment by alcaeus** [comment]
Next-gen 😛

**Comment by alcaeus** [comment]
flashy-thingie

**Comment by javian** [comment]
omg that's such an annoying gif ;|

**Comment by alcaeus** [comment]
Just look at it, you'll forget you every saw it.

**Pull request closed without merging**
