### PR TITLE
php53-v8js 0.6.4

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Do you think this could be an upstream issue @alcaeus ?

**Comment by alcaeus** [comment]
I'm not sure. I can give it a look and report back, but probably not until after the weekend.

**Comment by javian** [comment]
No problem. There's been 9 installs of this package for php5.3 since June 1st so waiting to merge is not a big issue.

**Comment by alcaeus** [comment]
Right - with that many installs I'm not going to bother checking if 0.6.4 actually supports PHP 5.3, especially in light of the recent discussion about dropping 5.3.

**Pull request closed without merging**
