### PR TITLE
php{55-72}-mongodb 1.4.0

### PR DESCRIPTION
**Pull request by bashofmann**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)? (only php72-mongodb)
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)? (only php72-mongodb)

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
This would resolve #4762

**Comment by jmikola** [comment]
Note that `ext-mongodb` 1.4.0 includes a new `./configure` option to utilize Secure Transport on macOS. Quoting the [1.4.0 release notes](https://github.com/mongodb/mongo-php-driver/releases/tag/1.4.0):

> This release overhauls the way the extension configures SSL libraries and adds support for LibreSSL and macOS native SSL (Secure Transport). When building from source, `configure` now supports a `--with-mongodb-ssl` option. This defaults to `auto`, which will first attempt to use OpenSSL, followed by LibreSSL, and finally Secure Transport (for macOS only, of course). Additionally, you may specify `openssl`, `libressl`, or `darwin` to force a particular library, or specify `no` to disable SSL entirely. Installing the driver via PECL will use the default `auto` behavior.

I would suggest replacing `"--with-openssl-dir=#{Formula["openssl"].opt_prefix}"` in the PHP 5.5+ formulae with `--with-mongodb-ssl=darwin`. This should address outstanding segfaults on macOS High Sierra due to BoringSSL:

 * https://github.com/Homebrew/homebrew-php/issues/4607
 * https://github.com/mongodb/mongo-php-driver/issues/681
 * https://github.com/mongodb/mongo-php-driver/issues/682

**Comment by bashofmann** [comment]
@jmikola I changed the formulas to use --with-mongodb-ssl=darwin. Works fine for me with our test suite.

**Comment by javian** [comment]
I think it would be better to stay with openssl since that would be the default in all other places where we use ssl. I'm assuming that it would have the same effect and keep the formula as close to what it's been previously.

**Comment by jmikola** [comment]
> I think it would be better to stay with openssl since that would be the default in all other places where we use ssl. I'm assuming that it would have the same effect and keep the formula as close to what it's been previously.

I'd argue that keeping OpenSSL in place is doing a disservice to those using Apache and High Sierra, since they're inevitably going to hit the BoringSSL issue. I'm not aware if Homebrew can take options at install time (if you wanted to make `--with-mongodb-ssl` configurable), but if not that will necessitate users resorting to building the extension from source outside of Homebrew.

I read your [httpd-users mailing list post](http://markmail.org/message/ysrcf25xiluydpfg) regarding the related OpenSSL/BoringSSL crashes with SNMP (from https://github.com/Homebrew/homebrew-core/pull/16067), but it's too early to say when/if that might be addressed upstream.

I'd also point out that the [libmongoc formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mongo-c-driver.rb#L30) already uses Secure Transport instead of OpenSSL. If anything, I might suggest changing this PHP formula depend on the `mongo-c-driver` Homebrew package and rely on loading libmongoc/libbson as system libraries (` --with-libbson=yes --with-libmongoc=yes`) instead of using the bundled versions we ship with the PECL package. That is the same approach used for other package managers (e.g. Remi's CentOS and Red Hat packages).

**Comment by javian** [comment]
I must have misunderstood the implementation then in the mongodb extension and using SecureTransport sounds like it would be the only option for now. I'm assuming the ssl implementation is isolated to the extension and has no dependencies in php at all so stacking different SSL implementations in different binaries would not end up being an issue (at least in this case) ?

As for you libmongoc option I think that sounds like a good plan moving forward and how we should implement it in the core formula.

**Comment by jmikola** [comment]
> I'm assuming the ssl implementation is isolated to the extension and has no dependencies in php at all so stacking different SSL implementations in different binaries would not end up being an issue (at least in this case)?

Early versions of the driver did utilize PHP and its OpenSSL extension for our socket communication, but this was changed in 1.2.0 with [PHPC-605](https://jira.mongodb.org/browse/PHPC-605). Since 1.2.0, all socket communication and TLS utilizes libmongoc directly. The only commonality is that our extension was still linking to libssl and libcrypto, as evidenced by the BoringSSL issue.

In 1.2.x and 1.3.x, we were still using the `PHP_SETUP_OPENSSL()` macro in `config.m4` to _detect_ OpenSSL the same way that PHP itself and other dependent extensions do. In 1.4.0 we also removed that and ported over libmongoc's own [`CheckSSL.m4`](https://github.com/mongodb/mongo-php-driver/blob/1.4.0/scripts/build/autotools/CheckSSL.m4) to now detect OpenSSL, LibreSSL, and Secure Transport on our own.

Hope that clears things up.

**Comment by brancengregory** [comment]
Bump

**Comment by javian** [comment]
Merged now @bashofmann and thanks for all the info @jmikola ! Potentially we need to review this if/when apache httpd is fixed but this should be good for now.

**Pull request closed without merging**
