### PR TITLE
composer 1.3.0-RC

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
The devel version doesn't seem to be a phar and needs to be compiled to work as expected.

**Comment by alcaeus** [comment]
Oh, right, I didn't see that. I'll get on it tomorrow morning.

**Comment by javian** [comment]
This versioning scheme might cause problems later but we'll see when we get there.

**Comment by javian** [comment]
Thanks @alcaeus !

**Comment by alcaeus** [comment]
> This versioning scheme might cause problems later but we'll see when we get there.

You mean just calling it "RC" instead of "RC-1"? I'd think if they need another release candidate, that would be "RC-2" to avoid confusion.

**Comment by javian** [comment]
The problem is that brew discards anything after the 0. Looking at their commit history they only released one RC for 1.2.0 so it should probably be ok

**Pull request closed without merging**
