### PR TITLE
Bump revision for php72-gearman

### PR DESCRIPTION
**Pull request by dasmfm**
In continuation of #4380.

- [+] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [+] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [+] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by alcaeus** [comment]
Thanks - looks like I missed this one. I originally checked all formulae to see if they were installable without errors, but apparently I missed some.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
This doesn't compile on high Sierra due to it's dependency on the failing gearman formula.

**Comment by dasmfm** [comment]
gearman formula fixed (https://github.com/Homebrew/homebrew-core/pull/18841)

@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
Thanks @dasmfm !

**Pull request closed without merging**
