### PR TITLE
couchbase: update to 2.2.0

### PR DESCRIPTION
**Pull request by avsej**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by ingenthr** [comment]
@avsej any comments on the failures there?

**Comment by avsej** [comment]
I think it is an environment issue, phpize in versions 5.3, 5.4 and 5.6 recorded outdated location of `sed`

```
/usr/local/opt/php53/bin/phpize: line 60: /usr/local/Library/ENV/4.3/sed: No such file or directory
```

It is not related to the couchbase extension, the php dists have to be rebuilt on new homebrew, and phpize scripts have to be fixed. I've checked it locally, with correct sed it works

**Comment by ablyler** [comment]
@avsej I was able to reproduce the build error by running: `brew install --build-bottle --verbose homebrew/php/php54-couchbase`.  Can you reproduce it by running that? Want to take a stab at fixing it?

**Comment by avsej** [comment]
@ablyler it is not couchbase extension bug.

I bet the issue will disappear once you will rebuild old php bottles (php53, php54, php55), because when they were built, the file `Library/ENV/4.3/sed` introduced in this patch https://github.com/Homebrew/brew/commit/4f06d131dfffc9de625697c2135262f624534a6e  was still inplace, and the bottle "remembered" it, and once you upgraded your tree to the state when https://github.com/Homebrew/brew/commit/a02be9eea204264ce48827ac365c8b53b986d66a applied, the `sed` executable has been moved, and is not accessible on the old place. Why don't you like using system sed? It is perfectly fine and suitable for `phpize` needs.

**Comment by javian** [comment]
I agree, rebuilding the bottles should solve the sed issue.

**Comment by javian** [comment]
@BrewTestBot please test this

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by avsej** [comment]
@javian @ablyler, so now it is green. anything else for merge?

**Comment by javian** [comment]
No that should be enough - merging right now.

**Comment by javian** [comment]
Thanks for the PR @avsej !

**Pull request closed without merging**
