### PR TITLE
msgpack: update to 0.5.7

### PR DESCRIPTION
**Pull request by lvht**

### CODE REVIEW

**Comment by ablyler** [comment]
@lvht can you add a bottle block to the formulas, so that binary bottles are created?

```
  bottle do
  end
```

**Comment by ablyler** [comment]
also, @lvht can you change the sha1 to a sha256?

**Comment by lvht** [comment]
@ablyler I am not familar with homebrew. What I want to do is just make the msgpack-0.5.7 available. Please contact to the original author to refactor this code. Thanks.

**Comment by ablyler** [comment]
@lvht no worries, I have made the changes in PR #2048

**Pull request closed without merging**
