### PR TITLE
pecl_http 2.6.0

### PR DESCRIPTION
**Pull request by s172262**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

### CODE REVIEW

**Comment by SMillerDev** [comment]
@s172262 could you squash the commits that are pointing to the same php version? You have multiple commits for 5.4 and 5.3

**Comment by s172262** [comment]
I installed and uninstalled `php53`, `php54` and `php56` for making this PR.(So I don't try over php7.)
May I divide this PR?

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by s172262** [comment]
Oh! Me too. I can't find `/usr/local/opt/php53/bin/php`. But service of `php53` had started.
```
$ brew services list
Name       Status  User        Plist
pulseaudio started s172262 /Users/s172262/Library/LaunchAgents/homebrew.mxcl.pulseaudio.plist
php56      stopped
zookeeper  started s172262 /Users/s172262/Library/LaunchAgents/homebrew.mxcl.zookeeper.plist
httpd      started s172262 /Users/s172262/Library/LaunchAgents/homebrew.mxcl.httpd.plist
jack       started s172262 /Users/s172262/Library/LaunchAgents/homebrew.mxcl.jack.plist
unbound    started root        /Library/LaunchDaemons/homebrew.mxcl.unbound.plist
php53      started s172262 /Users/s172262/Library/LaunchAgents/homebrew.mxcl.php53.plist
```

???

**Comment by SMillerDev** [comment]
Thanks @s172262 !

**Pull request closed without merging**
