### PR TITLE
php70-ds 1.0.4 (new formula)

### PR DESCRIPTION
**Pull request by Mikulas**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

This adds formula for php-ds extension
https://github.com/php-ds/extension

### CODE REVIEW

**Comment by javian** [comment]
Thanks for the submission @Mikulas ! Once the tests have passed I will have it merged.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by Mikulas** [comment]
Great :)

It failed but it seems transient

> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': Failed to connect to github.com port 443: Operation timed out

@BrewTestBot test this please

**Comment by javian** [comment]
Yes. There's something really weird going on with this PR because it doesn't get tested properly nor is a bottle built for it. As far as I can tell it all looks ok so I'm not sure what's going on.

**Comment by javian** [comment]
Ah I see what's going on now. You need to put the formula in the right directory.

You've put it in `Contributions/...` and it needs to go into the same directory as all the other Formulas `Formula/` . Can you move it there and squash and resubmit ?

**Comment by Mikulas** [comment]
Ah, sorry about that.

Rebased.

**Comment by javian** [comment]
Thanks for the submission @Mikulas - would you mind making a PR for PHP7.1 too ?

**Comment by Mikulas** [comment]
Thanks! Following up with #3443

**Pull request closed without merging**
