### PR TITLE
PHP 7.1.10

### PR DESCRIPTION
**Pull request by derrabus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
Thanks for the PR, if you look at [7.1.8](https://github.com/Homebrew/homebrew-php/pull/4353/files) you'll see it usually includes more files. Could you add changes for those?

**Comment by derrabus** [comment]
You mean bumping the revision numbers of all php71 packages? This looks unnecessary to me, but I can apply that change if you want me to.

**Comment by derrabus** [comment]
Done.

**Comment by alcaeus** [comment]
> This looks unnecessary to me, but I can apply that change if you want me to.

It's necessary for packages that rely on `PHP_SRC_TARBALL`: their bottles need to be recompiled for the new version to be applied, hence the revision bump.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
There seems to be a file conflict with php71-opcache - can you figure out why ?

**Comment by derrabus** [comment]
Done.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by derrabus** [comment]
I've bumped all packages to php 7.1.10. I've also changed the documentation URLs to HTTPs because your Jenkins was complaining about them. If there's anything else I can do to get this merged, please let me know.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by qkdreyer** [comment]
Any updates ?

**Comment by andig** [comment]
ping @javian any chance to release this?

**Comment by javian** [comment]
Thanks @derrabus !

**Pull request closed without merging**
