### PR TITLE
Update php-code-sniffer to 2.3.0

### PR DESCRIPTION
**Pull request by Zifius**

### CODE REVIEW

**Comment by alanthing** [comment]
@BrewTestBot test this please

**Comment by alanthing** [comment]
(trying to see if we can get a bottle built)

**Comment by Zifius** [comment]
Lazy lazy @BrewTestBot

**Comment by alanthing** [comment]
I was told it needs to be exactly...

**Comment by alanthing** [comment]
@BrewTestBot test this please

**Comment by alanthing** [comment]
We'll look at a bottle next time- thanks for submitting this PR.

**Pull request closed without merging**
