### PR TITLE
php56-grpc 1.0.0

### PR DESCRIPTION
**Pull request by simonkuang**
- [ y ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ y ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ y ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
The build ran into this error as far as I can tell
```
ast 150 lines from /Users/travis/Library/Logs/Homebrew/google-protobuf/01.autogen.sh:
2016-08-28 18:16:34 +0000
./autogen.sh
Google Mock not present.  Fetching gmock-1.7.0 from the web...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1582  100  1582    0     0  14571      0 --:--:-- --:--:-- --:--:-- 14648
[gmock-1.7.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of gmock-1.7.0.zip or
        gmock-1.7.0.zip.zip, and cannot find gmock-1.7.0.zip.ZIP, period.

```
Do you know why ?

**Comment by simonkuang** [comment]
@javian 
grpc use a private protobuf formula named `grpc/grpc/google-protobuf`, and there is a broken url in script 'autogen.sh'. Travis-ci throw out the error as it could not download any source from the url.

I have commit a PR(https://github.com/grpc/homebrew-grpc/pull/87) to fix this problem. just wait please.

**Comment by jcanizales** [comment]
The gRPC PR is merged now.

**Comment by simonkuang** [comment]
@jcanizales thank you for reminding.

**Comment by javian** [comment]
Thanks for having another look. I've triggered the Travis build and if that works fine then I'll build the bottles too and merge it.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by simonkuang** [comment]
@javian
thanks ;-P
I'm not familiar enough with github yet.

**Comment by javian** [comment]
Thank you for submitting this @simonkuang ! Does this extension also support other php versions and would you be willing to submit a PR for them as well ? You'll get the hang of GitHub quickly =)

**Pull request closed without merging**
