### PR TITLE
Add compat flag for icu4c 61.1

### PR DESCRIPTION
**Pull request by msbit**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes https://github.com/Homebrew/homebrew-php/issues/4828 as per https://github.com/Homebrew/homebrew-core/pull/25799/commits/2015b858dc88c27a448257108ae89f0d3e246f92

### CODE REVIEW

**Comment by SMillerDev** [comment]
please remove 5.3-5.5, if you're using those there's issues anyway.

**Comment by Schrank** [comment]
`__dir__` didn't work for me, `__FILE__` did.

But unfortunately I have no clue about Ruby or homebrew infrastructure.

Error for me:

-> % brew install php70-intl
Error: php70-intl: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/Abstract/abstract-php-extension

**Comment by msbit** [comment]
@Schrank did you manually edit the formula to put this change in place or are you using this commit?

I ask because if you manually editted the line and only changed `__FILE__` to `__dir__` then you will have missed the other change of also removing another level of directory backtracking, so altogether it should be:

```
-require File.expand_path("../../Abstract/abstract-php-extension", __FILE__)
+require File.expand_path("../Abstract/abstract-php-extension", __dir__)
```

**Comment by Schrank** [comment]
Perfect, I made it wrong! :D thanks for the info @msbit

**Comment by MikeMcQuaid** [comment]
As [announced on the 19th of January](https://brew.sh/2018/01/19/homebrew-1.5.0/) this tap will be archived by 31st March 2018. Various PHP formulae have been [migrated to Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-php/blob/master/tap_migrations.json). Thanks for your pull request anyway and sorry we couldn't include it. Please consider [maintaining this formula in your own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap).

**Pull request closed without merging**
