### PR TITLE
support minimum php version

### PR DESCRIPTION
**Pull request by BePsvPT**
This PR allows php-meta-requirement to specific the minimum php version.

Usage: 
　depends_on PhpMetaRequirement => [{min_version: _**version**_}]

### CODE REVIEW

**Comment by BePsvPT** [comment]
Fixes #3772

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
@javian could you please review this pull request?

**Comment by javian** [comment]
We won't be merging this now since we are in the process of migrating all the formulas to core.

**Pull request closed without merging**
