### PR TITLE
Upgrade php70 to 7.0.8

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
I'm curious why the official page has not been updated with the information about this new version yet.

**Comment by pinepain** [comment]
They follow their own procedure. It will be available later.

**Comment by ilovezfs** [comment]
Why are bottles being deleted?

**Comment by pinepain** [comment]
Because they will be updated with the new version later by bot.

**Comment by javian** [comment]
It is now out - http://php.net/ChangeLog-7.php#7.0.8

**Comment by javian** [comment]
@ilovezfs which bottles ?

**Comment by ilovezfs** [comment]
@javian https://github.com/Homebrew/homebrew-php/pull/3279/files#diff-20a46124144440dbf4351335b447866aL6

**Comment by javian** [comment]
@ilovezfs saw your message in the other PR so I understand now - thanks for pointing it out! @pinepain please revert the change to the bottle lines since it is not needed.

**Comment by pinepain** [comment]
Fixed.

**Comment by ablyler** [comment]
actually, we need to remove all the bottles for the php70* formulas that include the PHP_SRC_TARBALL constant so that the bot will rebottle them with the new version.  I'll take care of that now and merge this PR.  Thanks!

**Comment by pinepain** [comment]
@ablyler thanks! I saw you did that manually on per-bottle level. Do such things should be done by members or it's fine to provide PR with one commit per bottle? I see that ci system doesn't handle such PRs well.

**Comment by javian** [comment]
Wouldn't it be enough to make the revision match the php version used which would also then update the bottles ?

**Comment by ablyler** [comment]
I have a script I use to do it, I'll try to put it out on a repo somewhere so that others can use it.

**Comment by ablyler** [comment]
@javian that hasn't worked for me in the past.

**Pull request closed without merging**
