### PR TITLE
n98-magerun 1.97.22 (new formula)

### PR DESCRIPTION
**Pull request by mgeoffray**
Add n98 magerun tool

### CODE REVIEW

**Comment by javian** [comment]
Hi @mgeoffray thanks for the PR! It seems you have already submitted this to homebrew-core. Can you please submit the magerun2 pr that you posted in https://github.com/Homebrew/homebrew-core/pull/1498 on top of this. This the formula was accepted into core then we need to move it across so I won't merge this just yet.

**Comment by javian** [comment]
@mgeoffray please also inherit the AbstractPhpPhar instead of formula see https://github.com/Homebrew/homebrew-php/blob/master/Formula/phpunit.rb for an example.

**Comment by mgeoffray** [comment]
Hi @javian I fix the AbstractPhpPhar inclusion, and there is the magerun2 PR : https://github.com/Homebrew/homebrew-php/pull/3229

**Comment by UniqMartin** [comment]
I just created a PR (Homebrew/homebrew-core#1534) to perform the migration in `homebrew/core` and that should be pulled immediately after this is ready and gets pulled.

@mgeoffray I'm not very familiar with this PHP tap, but judging from the provided example formula you might need to replace the `install` method with a `phar_file` method. (And sorry for not redirecting your original PR immediately here and causing you extra work now!)

**Comment by mgeoffray** [comment]
@UniqMartin Don't worry about that, that is not a lot of work either ;)   
Maybe a silly question but as it is your merge request, how do I can modify the file ? I have to wait that yours is accepted and restart form master of homebrew-php ?

**Comment by UniqMartin** [comment]
> Maybe a silly question but as it is your merge request, how do I can modify the file ? I have to wait that yours is accepted and restart form master of homebrew-php ?

Don't worry about asking questions that might seem silly. 😸 I was talking about this PR and #3229, that are both created by you and that you should be able to modify. The PR created by me in `homebrew/core` should be fine as it just removes the file there and “redirects” users that might have already installed the `n98-magerun` formula to this tap, so they get updates in the future. Did this explanation make sense?

**Comment by mgeoffray** [comment]
OK totally, I did not understand that way but make sens yes !

**Comment by mgeoffray** [comment]
@UniqMartin The current Formula in homebrew-php will not conflict with the one in homebrew-core during installation or maintenance? https://github.com/Homebrew/homebrew-core/blob/master/Formula/n98-magerun.rb

**Comment by UniqMartin** [comment]
@javian I'll merge this PR together with Homebrew/homebrew-core#1534 once I have your :+1:. (To me this PR looks ready, but I want to make sure I'm in alignment with how this tap is normally maintained.)

**Comment by javian** [comment]
@UniqMartin The tests are failling due to a recent change in brew and the brewbot complains that the formula already exists. The formula looks fine though.

**Comment by UniqMartin** [comment]
Merged. Thank you for this contribution to Homebrew, @mgeoffray! :tada:

@javian I noticed you already fixed the Travis issue and it should be safe to ignore as long as the “default” build (Jenkins) passes. The audit errors will always be there for a migration as the test bot run won't know anything about the other PR that is part of this migration and the other PR can only be merged once this one is in. In summary: I believe everything should be fine. Massive thanks for the help!

**Comment by mgeoffray** [comment]
@UniqMartin Thank you !

**Comment by javian** [comment]
@UniqMartin thanks for sorting this out!

**Pull request merged**
