### PR TITLE
Updates xhgui to 0.4.0

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
@BrewTestBot test this

**Comment by cmckni3** [comment]
@BrewTestBot test this please

**Comment by cmckni3** [comment]
ping @alanthing

**Comment by alanthing** [comment]
I had this error upon fresh installation:

```
==> composer install
  Problem 2
    - slim/slim 2.3.1 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - slim/views 0.1.0 requires slim/slim >=2.0.0 -> satisfiable by slim/slim[2.3.1].
    - Installation request for slim/views 0.1.0 -> satisfiable by slim/views[0.1.0].
```

So, I added `php5x-mcrypt` as a dependency. I also filled in some of the example text in the caveats with actual paths to make installation a little quicker.

**Comment by cmckni3** [comment]
@alanthing Nice catch. I already had mcrypt installed but it is in the xhgui requirements.

Yeah I had to fix the redis and memcached formulae. It's recommended to use `opt_` methods. This is necessary when when building from source as well.

**Pull request closed without merging**
