### PR TITLE
Codeception 2.1.10 (fixed phars)

### PR DESCRIPTION
**Pull request by Zifius**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Zifius** [comment]
@ablyler @javian do I need to bump bottles or formula revision if the formula version didn't change but the hash was? Thanks

**Comment by javian** [comment]
@Zifius adding a revision line should do the trick. I've not fully understood the process but doing that we should be good.

**Comment by Zifius** [comment]
@javian but to the bottles I suppose after they are built? Adding revision to the formula itself causes a patch to be downloaded (see brew bot failure for the first commit)

**Comment by javian** [comment]
That's not your bottles though, its the php71 bottles that are failing to download since they've not been updated.

**Comment by Zifius** [comment]
Version 2.1.11 was released, will recreate PR

**Pull request closed without merging**
