### PR TITLE
php{55-72}-mongodb 1.3.0

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
So, build is failing due to dependency gymnastics. This version depends on PHP 7.2 RC1+ is seems. And that fails because it doesn't work with 1.2.9

So, can you move the update for the 7.2 extension from here to the 7.2RC2 commit? That should fix all this (or I hope so at least)

**Comment by alcaeus** [comment]
@SMillerDev done - php72-mongodb has been moved to #4465.

**Comment by SMillerDev** [comment]
Thanks @alcaeus

**Pull request closed without merging**
