### PR TITLE
Update Deployer version

### PR DESCRIPTION
**Pull request by antonmedv**
Update version
-----

### CODE REVIEW

**Comment by antonmedv** [comment]
Please, merge :)

**Comment by antonmedv** [comment]
Ping!

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @antonmedv ! Next please use the commit message format to  

deployer 5.0.0   

or whatever version is commited. Then I don't have to change it when merging =)

**Comment by antonmedv** [comment]
Ok.

**Pull request closed without merging**
