### PR TITLE
Bump revision for imagick formulae

### LINKED ISSUE #3842: Getting php71-imagick error
## Description

PHP scripts on the CLI output an error with loading php71-imagick.
Brew is updated and upgraded.
The error is on the `php-v` section.

## Context and Logs

Parameter | Value
--------- | ------------------
**OS X Version:**       | 10.12.1
**Homebrew Version:**   | 1.1.2
**PHP Version in use:** | 7.1.0
**Xcode Version:**      | 8.1.0.0.1.1476494586

**Output of gcc -v:**
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Output of php -v:**
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/opt/php71-imagick/imagick.so' - dlopen(/usr/local/opt/php71-imagick/imagick.so, 9): Library not loaded: /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
  Referenced from: /usr/local/opt/php71-imagick/imagick.so
  Reason: image not found in Unknown on line 0
PHP 7.1.0 (cli) (built: Dec 11 2016 22:53:08) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

This should fix #3842.

### CODE REVIEW

**Comment by alcaeus** [comment]
@javian tests fail because of `brew doctor` reporting an outdated xcode version as well as this error:

> Error: No available formula with the name "homebrew/apache/httpd24" 
Please tap it and then try again: brew tap homebrew/apache
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Not sure what is causing this error...

**Comment by javian** [comment]
Yeah I saw that too - not sure where its coming from but I'll ask the others.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
This was related to a bug that has now been fixed so it should pass now afaik.

**Comment by alcaeus** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
```
==> brew linkage --test php56-dmtx
==> FAILED
Missing libraries:
  /usr/local/opt/imagemagick/lib/libMagickCore-6.Q16.2.dylib
  /usr/local/opt/imagemagick/lib/libMagickWand-6.Q16.2.dylib
```
Error only shows on ElCap and Yosemite

**Comment by javian** [comment]
The dmtx package seems to not be maintained for the past two years and there's been 18 installs since the 1st of september. We can probably safely pass this and see if it causes issues for any dmtx users.

**Pull request closed without merging**
