### PR TITLE
Xdebug 2.4.1 for PHP 7.1

### PR DESCRIPTION
**Pull request by Zifius**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks for the submission @Zifius - can you please use the notation 

`php71-xdebug 2.4.1`

next time so we don't have to rebase the PR ?

**Comment by Zifius** [comment]
@javian No problem! Sorry, which notation do you mean?

**Comment by javian** [comment]
When you commit replace the title you used now with

<formula> <version>

**Comment by Zifius** [comment]
Ah yes, ok - got it

**Comment by javian** [comment]
This doesn't seem to compile since it doesn't support php <7.1 as far as I can read from the logs.

**Comment by Zifius** [comment]
Then I wonder how the original php71-xdebug formula was compiled :)

**Comment by javian** [comment]
I don't know to be honest but I can only see that it did pass.

**Comment by javian** [comment]
They added a check to not allow php 71 to compile which didn't exist in 2.4.0

**Comment by javian** [comment]
here's the culprit https://github.com/xdebug/xdebug/blob/xdebug_2_4/config.m4 and xdebug doesn't have issues open on github so I haven't filed a question or issue report with them/him.

**Comment by Zifius** [comment]
Ok, I asked on twitter

**Comment by Zifius** [comment]
Got a response: "PHP 7.1 support is for 2.5. It's not stable enough for a 2.4.x release. I record issues on https://bugs.xdebug.org, not on GitHub." so closing the PR

**Comment by javian** [comment]
Thanks for looking into it @Zifius !

**Pull request closed without merging**
