### PR TITLE
Added Mustache extension for php5.5 & 5.6

### PR DESCRIPTION
**Pull request by Stubbs**
Needs homebrew/homebrew#40626 to be accepted before this can be merged.

### CODE REVIEW

**Comment by alanthing** [comment]
If this will work on PHP 5.3 and 5.4, could you please add formula files for those as well?

**Comment by alanthing** [comment]
Thanks. Once your upstream is approved, leave a comment here and I will get the Brew Test Bot to cycle through again.

**Comment by Stubbs** [comment]
Can someone have a look at the last few comments on Homebrew/homebrew#40626 and let me know if you'd accept that PR on the homebrew-php repo instead?

**Comment by ablyler** [comment]
@Stubbs: I'll get this in soon, working on getting the brew bot fixed up to create bottles for this and other things.

**Comment by ablyler** [comment]
@BrewTestBot please test again.

**Comment by Stubbs** [comment]
Np @ablyler , just let me know if there's anything I need to do.

**Pull request closed without merging**
