### PR TITLE
Fixed compilation of php**-intl against icu4c 59.1

### PR DESCRIPTION
**Pull request by derrabus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

This PR fixes the compilation of the php intl packages against icu4c 59.1 which was introduced with Homebrew/homebrew-core#16720. Note that I could not manage to compile php 5.3 against the new ICU version.

### CODE REVIEW

**Comment by alcaeus** [comment]
Works for me. Can you update php72-intl as well?

**Comment by derrabus** [comment]
Done.

**Comment by derrabus** [comment]
Anything I can do about the CI checks? They don't feel related to my changes.

**Comment by moderndeveloperllc** [comment]
@derrabus If you check, they are related to your code:
```
Error: 2 problems in 1 formula
homebrew/php/php72-intl:
  * Stable: version 7.2.0beta2 is redundant with version scanned from URL
  * Stable version URLs should not contain beta
```

**Comment by alcaeus** [comment]
@derrabus 
```
homebrew/php/php72-intl:
  * Stable: version 7.2.0beta2 is redundant with version scanned from URL
  * Stable version URLs should not contain beta
```

```
homebrew/php/php54-intl:
  * macOS has been 64-bit only since 10.6 so ENV.universal_binary is deprecated.
  * macOS has been 64-bit only so build.universal? is deprecated.
```

This last one also affects php55-intl and php56-intl, you just need to drop the line. This was only changed semi-recently, so the first formula update since then causes failure.

**Comment by derrabus** [comment]
Okay, but that's what I meant. Those issues are present in master already. It's not my PR that caused them. Anyway, I've removed the deprecated lines. But I don't know how to fix the check about the "beta" keyword in the download URL.

**Comment by derrabus** [comment]
Remaining CI failures:

* The error with php54-intl and libjpeg.8.dylib will be fixed with #4379.
* php70-http/php71-http: This really looks unrelated.
* php72-intl: See my previous comment. I did not cause it and I don't know how to fix it.

**Comment by javian** [comment]
Thanks for submitting this. You need to add one more thing in all the Formulas for it to work properly
```
diff --git a/Formula/php72-intl.rb b/Formula/php72-intl.rb
index d3a8953..c6c5b53 100644
--- a/Formula/php72-intl.rb
+++ b/Formula/php72-intl.rb
@@ -15,7 +15,11 @@ class Php72Intl < AbstractPhp72Extension
   sha256 PHP_CHECKSUM[:sha256]
   version PHP_VERSION
 
+  needs :cxx11
+
   def install
+    ENV.cxx11
+
     Dir.chdir "ext/intl"
 
     safe_phpize
```

**Comment by ilovezfs** [comment]
For 53,
```
diff --git a/Formula/php53.rb b/Formula/php53.rb
index 09897cc..bebe8c1 100644
--- a/Formula/php53.rb
+++ b/Formula/php53.rb
@@ -54,4 +54,9 @@ class Php53 < AbstractPhp
     url "https://gist.githubusercontent.com/javian/6d63097c8c175045aa75ca48a6b8826b/raw/ca7bad287e3af72b83fbb5f7d03186b5da2e65ae/multi-sapi-5.3.29-homebrew.patch"
     sha256 "bdde5c0c1f9d2450d8d9d0a32882e1ee0008d8339eacf919e273e6f7937e7461"
   end
+
+  patch do
+    url "https://gist.githubusercontent.com/ilovezfs/192a21d13ce0c40dcaa48617f1733097/raw/0856488df0e8190476d64ae68642670aebe8fbb3/gistfile1.txt"
+    sha256 "8ed93dee54d82a1c48703c7b1348bd4cd61ed80f377d0d6d419cf38ff1274f42"
+  end
 end
```

Also, should have `needs :cxx11` on each of them above the `def install`

**Comment by javian** [comment]
And we seem to have a fix for 5.3 in line so it should come.
```
< #define ZEND_NS_NAME(ns, name)            ns"\\"name
---
> #define ZEND_NS_NAME(ns, name)            ns "\\" name
```
needs to be changed before running make in `include/php/Zend/zend_API.h`

**Comment by ilovezfs** [comment]
https://gist.githubusercontent.com/ilovezfs/192a21d13ce0c40dcaa48617f1733097/raw/0856488df0e8190476d64ae68642670aebe8fbb3/gistfile1.txt in the patch block above makes that change.

**Comment by derrabus** [comment]
Thank you @ilovezfs. You patch indeed did the trick for php 5.3. I'm updating the PR at the moment.

**Comment by javian** [comment]
Looks good, I'll get it merged a little later.

**Comment by javian** [comment]
This build needs to be split up per php version since compiling them all times out on the build system.

**Comment by javian** [comment]
I'm currently rebuilding php53 and 54 separately so those formulas don't need updating.

**Comment by javian** [comment]
This has been superseded by other PRs. Closing and thank you @derrabus !

**Comment by pedropcruz** [comment]
I just post my problem here: #4664

**Pull request closed without merging**
