### PR TITLE
Add PHP 7.1.0-alpha.1 core formula (php71)

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

As per https://github.com/Homebrew/homebrew-php/issues/3271.

Known issues with PHP 7.1.0 alpha1:

 - xdebug won't compiled due to bug with `php_log_err macro` https://bugs.xdebug.org/view.php?id=1314#c3635 (already fixed in https://github.com/php/php-src/commit/d2bc82586b67882fdcdabac8e05cfbb4104bfd47).

 While this is already fixed less likely we need to patch php ourselves for that, based on [7.1 release schedule](https://wiki.php.net/todo/php71) next alpha will be available on Jun 23 2016, so we can ignore this bug or wait for alpha2 or apply that fix in fork or beg for alpha1.5.

### CODE REVIEW

**Comment by pinepain** [comment]
Build is red due to timeout, what is the best way to handle that? //cc @javian

**Comment by javian** [comment]
I think we need to seperate all the formulas and the core and submit the core stuff first. Then we can add all the single formulas individually since the test system is not really built to test multiple formulas at once.

**Comment by pinepain** [comment]
Now we have it read due to php headers. I guess it's fine.

**Comment by pinepain** [comment]
@javian I guess that's enough for single PR. Will provide more formulae in separate PR(s).

**Comment by pinepain** [comment]
Closing in a favor of https://github.com/Homebrew/homebrew-php/pull/3274

**Pull request closed without merging**
