### PR TITLE
Update xdebug to 2.3.2

### PR DESCRIPTION
**Pull request by j0k3r**
http://xdebug.org/updates.php#x_2_3_2

### CODE REVIEW

**Comment by localheinz** [comment]
:+1:

**Comment by alanthing** [comment]
The 2.3.x branch caused a ton of problems the last time we had it in. Let me do some testing before we accept this PR.

**Comment by j0k3r** [comment]
@alanthing yep, I also got a lot of problem with some segfault on coverage. I'm using the 2.3.2 since few days now without any problems.

**Comment by alanthing** [comment]
Ah, so it was 2.3 and 2.3.1 that had issues... I'll revisit this soon. Thanks for the feedback @j0k3r.

**Pull request closed without merging**
