### PR TITLE
Bump revisions for php72 extensions

### LINKED ISSUE #4373: php72-mongodb bottle is compiled against wrong API
## Description

Installed php72-mongodb from bottles and got an API version mismatch:
```
PHP Warning:  PHP Startup: mongodb: Unable to initialize module
Module compiled with module API=20160303
PHP    compiled with module API=20170718
These options need to match
 in Unknown on line 0
```

I'm confused as to how this can happen - do we need to bump revisions for a bunch of formulae, or how did we end up with different API versions in the bottles?

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 10.12.6
**Homebrew version:**   | Homebrew 1.3.1-24-g67b20d9
**PHP version in use:** | PHP 7.2.0beta2 (cli) (built: Aug  7 2017 16:06:18) ( NTS )
**Xcode version:**      | Xcode 8.3.3 Build version 8E3004b

**Output of `gcc -v`:**
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Install log:**

```
$ brew install php72-mongodb
==> Installing php72-mongodb from homebrew/php
==> Downloading https://homebrew.bintray.com/bottles-php/php72-mongodb-1.2.9.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/86/868bd2b7fe72fc77ab46a493615633894c2e8d2fbd7bd656d51e3bed7548c6fb?__gda__=exp=1502374870~hmac=b0c77f7ea23b5013cd9752c15e
######################################################################## 100.0%
==> Pouring php72-mongodb-1.2.9.sierra.bottle.tar.gz
==> Caveats
To finish installing mongodb for PHP 7.2:
  * /usr/local/etc/php/7.2/conf.d/ext-mongodb.ini was created,
    do not forget to remove it upon extension removal.
  * Validate installation via one of the following methods:
  *
  * Using PHP from a webserver:
  * - Restart your webserver.
  * - Write a PHP page that calls "phpinfo();"
  * - Load it in a browser and look for the info on the mongodb module.
  * - If you see it, you have been successful!
  *
  * Using PHP from the command line:
  * - Run `php -i "(command-line 'phpinfo()')"`
  * - Look for the info on the mongodb module.
  * - If you see it, you have been successful!
==> Summary
🍺  /usr/local/Cellar/php72-mongodb/1.2.9: 4 files, 644.9KB
```

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes #4373 and #4375. I've installed all php72 extensions and fixed those that caused issues. Only exception: php72-imagick as that's contained within #4363.

### CODE REVIEW

**Comment by javian** [comment]
This needs to be split up, the build took too long.

**Comment by alcaeus** [comment]
I was afraid it would, but opted for the lazy approach first. I'll have to script something, so I'll open these later today or tomorrow.

**Comment by alcaeus** [comment]
I've created the first batch of pull requests, I'll create the next batch once the build system has had time to process these pull requests.

**Comment by alcaeus** [comment]
Looks like I still overwhelmed the build system - I forgot that each PR spawns 3 builds. I'll create the remaining pull requests one by one over the next few days.

**Comment by javian** [comment]
I'll close this PR since the extensions have been submitted outside of this specific PR.

**Pull request closed without merging**
