### PR TITLE
Update grpc formula to 1.6.0

### PR DESCRIPTION
**Pull request by stanley-cheung**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by stanley-cheung** [comment]
I can fix the http vs https issue

**Comment by stanley-cheung** [comment]
@javian Fixed the project homepage URL

**Comment by javian** [comment]
Can you rename the commit to `php-grpc 1.4.1` and squash the commits ?

**Comment by stanley-cheung** [comment]
@javian Done. thanks.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by stanley-cheung** [comment]
@javian Friendlyping

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by SMillerDev** [comment]
@stanley-cheung I can merge this now but 1.6.0 is latest. You might want to update again.

**Comment by SMillerDev** [comment]
@BrewTestBot test this please

**Comment by stanley-cheung** [comment]
@SMillerDev Updated to version 1.6.0 Please check. Thanks!

**Comment by SMillerDev** [comment]
Thanks @stanley-cheung !

**Pull request closed without merging**
