### PR TITLE
Add xdebug-osx 1.0 (new formula)

### PR DESCRIPTION
**Pull request by mandrean**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

**Description:**
> Xdebug is a must have extension for PHP, although the times you don't actually need it, it's a drag.
> 
> This simple script allows to toggle on and off Xdebug and is meant for anyone running PHP and Xdebug installed via Homebrew.

It's great to have. I use it all the time to toggle Xdebug.

### CODE REVIEW

**Comment by mandrean** [comment]
Note: because of https://github.com/Homebrew/homebrew-php/blob/master/Requirements/php-meta-requirement.rb, line 31:

**Comment by mandrean** [comment]
Why does this fail with:

**Comment by mandrean** [comment]
Bump

All checks pass!

**Comment by mandrean** [comment]
@javian Bump! All checks pass.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by mandrean** [comment]
@javian All checks pass!

**Comment by javian** [comment]
There we go. Sorry that it took a while.

**Comment by mandrean** [comment]
Awesome! Thanks.

**Comment by w00fz** [comment]
Thanks guys, this is really great.

**Comment by javian** [comment]
@w00fz did ever consider renaming the script to xdebug-toggle or something similar to match the functionality of it ? Calling it xdebug might confuse people =)

**Comment by mandrean** [comment]
+1 for renaming it `xdebug-toggle`

**Comment by w00fz** [comment]
So I went ahead and renamed to `xdebug-toggle` (I left a `xdebug` symlink just in case). How should I go about now? Just tag-release to a new version and then open a PR here for this line change? https://github.com/Homebrew/homebrew-php/blob/master/Formula/xdebug-osx.rb#L26

**Comment by javian** [comment]
@w00fz yes , you also need to update the hash and the version number

**Comment by w00fz** [comment]
@javian thanks, on it.

**Pull request closed without merging**
