### PR TITLE
php55-mongodb 1.2.0alpha-3

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus ! Just want to point out that 
```
Warning: Nonstandard bump subject: php55-mongodb 1.2.0alpha-3
Warning: Subject should be: php55-mongodb 1.2.0alpha3 (devel)
```
so if you update the devel version please add it to the commit message.

**Comment by alcaeus** [comment]
> so if you update the devel version please add it to the commit message

Is there a spot where I can read about commit naming rules?

**Comment by javian** [comment]
This was the best I could find - https://github.com/Homebrew/brew/blob/master/docs/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md

**Comment by alcaeus** [comment]
Thanks, got it! 👍

**Pull request closed without merging**
