### PR TITLE
drush 8.1.8

### PR DESCRIPTION
**Pull request by BePsvPT**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by BePsvPT** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
I doesn't pass because the drupal code sniffer formula can't be downloaded. I tried updating it #3878 but the sniffer seems to have changed in recent version so I doesn't pass either with the recent formula.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @BePsvPT !

**Pull request closed without merging**
