### PR TITLE
igbinary 2.0.3

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by javian** [comment]
There are a lot of dependencies to this formula - do they still work even after upgrading to this version or do they need a new revision ?

**Comment by BePsvPT** [comment]
Sorry, i didn't test other formulas that depends with this formula. Is there any suggestion for this situation?

**Comment by javian** [comment]
Thanks @BePsvPT ! We'll see if the dependencies fails and we can issue a revision bump for those that do.

**Comment by javian** [comment]
@BePsvPT I just realised that the only thing this formula does it to provide the source code. You should update the php??-igbinary.rb files - can you do that ?

**Pull request closed without merging**
