### PR TITLE
phpunit 6.3.0

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by BePsvPT** [comment]
@javian 

I think the following error is not formula syntax problem. There is already this symbolic link.

```
Error: 2 problems in 1 formula
homebrew/php/phpunit:
  * Formula has other versions so create a versioned alias:
      cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Aliases
      ln -s ../Formula/phpunit.rb phpunit@6.3
  * Formula has invalid versioned aliases:
      phpunit@6.3
```

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks @BePsvPT !

**Pull request closed without merging**
