### PR TITLE
Prevent "Symbol not found" error in php56-memcache formula. Fixes #1366

### LINKED ISSUE #1366: dyld: lazy symbol binding failed: Symbol not found: _mmc_queue_pop
After installing the devel version of php53-memcache php is not working anymore with the error in the title. This thread contains the answer, 

> As David mentioned in the comments, when building the memcache plugin, NOT memcached itself, you have to add run configure like this:
> 
> `MACOSX_DEPLOYMENT_TARGET=10.7 CFLAGS='-fgnu89-inline' LDFLAGS='-fgnu89-inline' CXXFLAGS='-fgnu89-inline' ./configure`

but I can't get it to work. I have tried adding to the formula like so:

```
    safe_phpize
    system "MACOSX_DEPLOYMENT_TARGET=10.7 CFLAGS='-fgnu89-inline' LDFLAGS='-fgnu89-inline' CXXFLAGS='-fgnu89-inline' ./configure", "--prefix=#{prefix}",
                          phpconfig
    system "make"
```

But that failed on install. I tried pasting `MACOSX_DEPLOYMENT_TARGET=10.7 CFLAGS='-fgnu89-inline' LDFLAGS='-fgnu89-inline' CXXFLAGS='-fgnu89-inline'` in the Terminal before running

```
$ brew install --devel php53-memcache
```

But that didn't work as I still get the error in the title.

Any ideas how to fix?

Some details:
OS X 10.9.5

```
$ otool -L /usr/local/Cellar/php53-memcache/3.0.8/memcache.so 
/usr/local/Cellar/php53-memcache/3.0.8/memcache.so:
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

I checked the options, but did not see anything that looks like what I need?

```
$ brew options php53-memcache
--without-config-file
    Do not install extension config file
--without-homebrew-php
    Ignore homebrew PHP and use default instead
--devel
    install development version 3.0.8
--HEAD
    install HEAD version
```

### PR DESCRIPTION
**Pull request by JohnAlbin**
When installing php56-memcache, several of us are seeing:

```
dyld: lazy symbol binding failed: Symbol not found: _mmc_queue_free
  Referenced from: /usr/local/opt/php56-memcache/memcache.so
  Expected in: flat namespace
```

This PR fixes it per @steel-track's work in #1366.

### CODE REVIEW

**Comment by javian** [comment]
Thanks @JohnAlbin - would you mind submitting PRs for the other php versions as well ?

**Comment by JohnAlbin** [comment]
I updated the branch so that all these files include the new lines:

```
Formula/php53-memcache.rb
Formula/php54-memcache.rb
Formula/php55-memcache.rb
Formula/php56-memcache.rb
```

**Comment by javian** [comment]
@JohnAlbin perfect, I'll merge it tonight. Thanks !

**Comment by javian** [comment]
Thanks for the submission @JohnAlbin !

**Pull request closed without merging**
