### PR TITLE
Update revision for imagemagick-dependent formulae

### LINKED ISSUE #2766: php70-imagick has warnings
After latest brew update I'm getting the following error from every php script that executes:

Warning: Version warning: Imagick was compiled against Image Magick version 1682 but version 1683 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Fixes #2766 (again).

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus ! May I ask you to fix 
```
homebrew/php/php55-imagick:
  * macOS has been 64-bit only since 10.6 so ENV.universal_binary is deprecated.
  * macOS has been 64-bit only so build.universal? is deprecated.
```
in a seperate PR ? I will merge this now since we need the bottles but to make the build pass green those things needs to get addressed in the future.

**Comment by alcaeus** [comment]
Oh, yeah. I have the changes ready, just forgot to push them. I'll submit a bunch of these separately - how many formulae can the build system handle?

**Comment by javian** [comment]
@alcaeus it depends mostly on the number of dependencies and the number of formulas that depends on the formula itself. For php modules we can probably do 10-15 without a problem.

**Comment by alcaeus** [comment]
@javian Alright - I'll get to work on updating them soon.

**Pull request closed without merging**
