### PR TITLE
Fix up php53 audit errors

### PR DESCRIPTION
**Pull request by msbit**
Namely:
  * `option` (line 29) should be put before `depends_on` (line 27)
  * Options should begin with with/without. Migrate '--disable-zend-multibyte' with `deprecated_option`.

- ☑️  Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- ☑️  Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- ☑️  Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by msbit** [comment]
CI errors due to not tapping `homebrew/versions`?

`Error: No available formula with the name "homebrew/versions/bison27"`

**Comment by msbit** [comment]
`homebrew/dupes` removed in https://github.com/Homebrew/homebrew-php/pull/4059

**Comment by msbit** [comment]
Looks like `homebrew/versions/bison27` has been properly removed now, so this will depend on https://github.com/Homebrew/homebrew-php/pull/4049

**Comment by msbit** [comment]
@javian let me know if this is actually something you think is worth pursuing (particularly in light of https://github.com/Homebrew/homebrew-php/pull/3689); it looks like the CI failures are unrelated to the changes.

**Comment by javian** [comment]
@msbit the cause of the ci build errors is the pthreads module which forces php to be built with threadsafe support. Since all other bottled modules are built for non-threadsafe php some of them will fail which causes the CI errors.

**Comment by javian** [comment]
@BrewTestBot test this please

**Pull request closed without merging**
