### PR TITLE
Add php71-mcrypt formula

### PR DESCRIPTION
**Pull request by pinepain**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by pinepain** [comment]
Audit do not pass for some strange reasons:

without `depends_on "libtool" => :linked`:

```
$ brew audit --oneline Formula/php71-mcrypt.rb
php71-mcrypt:
  * Formulae are required to declare all linked dependencies.
    Please add all linked dependencies to the formula with:
      depends_on "libtool" => :linked
Error: 1 problem in 1 formula
```

with it:
```
$ brew audit --oneline Formula/php71-mcrypt.rb
php71-mcrypt:
  * libtool dependency should be
      depends_on "libtool" => :build
    Or if it is indeed a runtime dependency
      depends_on "libtool" => :run
Error: 1 problem in 1 formula
```
Can someone look into what's wrong, please?

**Comment by javian** [comment]
This is weird becuase libtool is required by php and is not listed as a dependency since its inlucluded in OSX. I'll see if I can dig some more.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
This looks like it was caused by a commit in brew and partly reverted here https://github.com/Homebrew/brew/pull/598 - thanks for the submission @pinepain !

**Pull request closed without merging**
