### PR TITLE
terminus@0.13 0.13.6 (new formula)

### PR DESCRIPTION
**Pull request by jribe**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

Terminus 1.0 is a major breaking change and some people/organizations (like me) need access to 0.x while we upgrade.

### CODE REVIEW

**Comment by jribe** [comment]
My cursory scan of the logs looks like the Jenkins failure may have been an intermittent issue. Can somebody rekick it?

**Comment by javian** [comment]
@jribe I'll trigger the build once more but you right - it seems to have been a CI issue not related to the code. I would however like to ask you to rename the formula to  `terminus@0.13` to keep it more in line with other versioned formulas.

**Comment by jribe** [comment]
Renamed to `terminus@0.13`

**Comment by javian** [comment]
Thanks for the submission @jribe !

**Comment by javian** [comment]
@jribe I just realized that this now conflicts with the `terminus` formula since they both share the same binary name. Would you prefer that a `conflicts_with` is added to prevent this or should we rename the binary for the legacy terminus when its installed ?

**Comment by javian** [comment]
And just for claritys sake, if conflicts_with is added then you can't have both formulas installed at the same time-

**Comment by jribe** [comment]
`conflicts_with` would be preferable for our usage. I would've added that myself, but I wasn't sure how.

**Comment by javian** [comment]
@jribe here's an example
`conflicts_with "php54-apcu", :because => "Provides conflicting functionality"` from https://github.com/Homebrew/homebrew-php/blob/master/Formula/php54-apc.rb . Here's another one from core `conflicts_with "jam", :because => "both install a 'jam' binary"` from ftjam.rb

**Comment by javian** [comment]
@jribe #4022 is the suggested way of doing it. This will produce an additional line in the caveats saying
```
This is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/terminus@0.13/bin:$PATH"' >> ~/.zshrc
```
and resolve the conflict which I think would be sufficient.

**Pull request closed without merging**
