### PR TITLE
wp-cli 1.2.0

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by pstonier** [comment]
+1

**Comment by javian** [comment]
Duplicate of #4193. Closing.

**Comment by danielbachhuber** [comment]
@javian Do I no longer need to submit pull requests for new versions?

**Comment by BePsvPT** [comment]
@danielbachhuber currently, homebrew-updater will check for new versions automatically. If you want to handle wp-cli new version, i will remove it from checking list.

**Comment by javian** [comment]
@danielbachhuber it seems to be working quite well with the @BePsvPT application so I think we can give it a go having that manage the updates for now . I'll merge your 1.2.0 and then we can manage the next update through @BePsvPT

**Comment by danielbachhuber** [comment]
> I'll merge your 1.2.0 and then we can manage the next update through @BePsvPT

👌 works for me

**Pull request closed without merging**
