### PR TITLE
phan 0.11.0

### PR DESCRIPTION
**Pull request by BePsvPT**
---

Pull request opened by [homebrew-updater](https://github.com/BePsvPT/homebrew-updater) project.

### CODE REVIEW

**Comment by TysonAndre** [comment]
See the notes for https://github.com/phan/phan/releases/tag/0.11.0 - It's too early to release 0.11.0, It's intended for analysis of php 7.2 projects, not 7.1 projects (The differences are fairly minor. composer.json for the 0.11 releases requires php 7.2 to avoid accidental upgrades.)

See https://github.com/Homebrew/homebrew-php/pull/4585 for upgrading 0.10/0.8

**Comment by SMillerDev** [comment]
This is a pre-release. I think at best this should be in `devel` for the phan formula

**Comment by BePsvPT** [comment]
Currently, It seems that testing environment does not support php 7.2. Is there anything that I can do?

**Comment by javian** [comment]
They seems to be tagging all releases as development so its not unique to the new version - I think we should add it. 
```
The 0.11.x versions will be tracking syntax from PHP versions 7.2.x and are runnable on PHP 7.2+.
Please use version 0.10.x if you're using PHP 7.1, or 0.8.x if you're using PHP 7.0
See the file NEWS for what has changed in this version.
```
so lets track those 3 versions and remove 0.9 which currently is in the repo. This is really annoying to be honest that they can't provide one version for all =|

**Comment by BePsvPT** [comment]
Should I close this  and send new pull requests?

**Comment by javian** [comment]
@BePsvPT yes please do

**Pull request closed without merging**
