### PR TITLE
terminus 0.13.2

### PR DESCRIPTION
**Pull request by milsyobtaf**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by ilovezfs** [comment]
do you mind rebasing this? Thanks!

**Comment by milsyobtaf** [comment]
I think I did this correctly, but if not I can just wipe out this branch and try fresh. Sorry for the troubles.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
lets try again and see if the problem reoccurs

**Comment by javian** [comment]
@milsyobtaf not sure whats up to be honest but it seems to be complaining about git and that the pr is not ok for some unknown reason

**Comment by wturnerharris** [comment]
Yo what's the status of this? It's two lines changed? Is it GitHub new permissions?

The gzipped package is correct, and the sha256 matches. I'm not a regular contributor, so I'm not sure what the hold-up is. For now, I was able to install by decompressing the package, running composer, and (because I'm lazy) renaming the new package to the currently installed brew version.

http://recordit.co/K8GTEcvR0j

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@milsyobtaf would you be able to fix this so we can merge it ?

**Comment by ilovezfs** [comment]
Closing in favor of https://github.com/Homebrew/homebrew-php/pull/3687.

**Comment by ilovezfs** [comment]
@milsyobtaf thanks for this PR! There's a new version so I've opened #3687 but maybe you can do the next update!

**Comment by javian** [comment]
This has now been superceded by the next version.

**Comment by wturnerharris** [comment]
Oh great. Thanks.

**Pull request closed without merging**
