### PR TITLE
php-code-sniffer 2.7.1

### PR DESCRIPTION
**Pull request by Zifius**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by Zifius** [comment]
@javian Hi, I guess I need some of your help on fixing the tests here

**Comment by javian** [comment]
@Zifius that one was new to me. I can't test it right now but I'm assuming you are not seeing this on your machine since you tested it locally.

**Comment by Zifius** [comment]
I cheated there a bit with the checkmarks - was in a hurry, I'll try to build locally and get back to you

**Comment by Zifius** [comment]
@javian Apparently that replacement is no longer needed, see https://github.com/squizlabs/PHP_CodeSniffer/commit/63f2c6b23132f14da050817c6740a7240307884a
I also fixed an audit error

**Comment by javian** [comment]
Thanks for the submission @Zifius ! Much appreciated.

**Comment by Zifius** [comment]
Thank you @javian, I'm always happy to contribute to this project!

**Pull request closed without merging**
