### PR TITLE
drupal-code-sniffer 8.x-2.0

### PR DESCRIPTION
**Pull request by arnested**

### CODE REVIEW

**Comment by alanthing** [comment]
I see this is a 8.x release; is still backwards compatible with Drupal 7 and/or 6? If it's not, we may want to offer 7.x by default and provide 8.x as a devel/head option since Drupal 8 is not released yet. If that's not the case and it is backwards compatible, we can get this pushed through.

**Comment by arnested** [comment]
This is backwards compatible.

**Comment by arnested** [comment]
I also added the DrupalPractice standard which is now part of Drupal Coder Sniffer.

This time the test build went fine.

**Comment by alanthing** [comment]
Great, thanks!

**Pull request closed without merging**
