### PR TITLE
php70 7.0.17

### PR DESCRIPTION
**Pull request by alcaeus**
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by javian** [comment]
Thanks @alcaeus !

**Comment by neutric** [comment]
Just curious: what is the deal with these "symbol not found" errors when testing xdebug? I had these in 7.0.16 (#4003) as well.

**Comment by javian** [comment]
@neutric the reason is that one of the modules requires a thread safe binary which means that php is compiled with thread safety which is not compatible with the bottled non-threadsafe php modules which causes the errors.

**Comment by neutric** [comment]
@javian Thanks for taking time to explain, I appreciate it!

**Comment by javian** [comment]
@neutric thanks for understanding that tounge twister sentence - it was hard to read it even for me at first glance looking back at it =)

**Comment by neutric** [comment]
It wasn't hard to understand, don't worry.

**Pull request closed without merging**
