### PR TITLE
Drupalconsole 1.0.0-rc6

### PR DESCRIPTION
**Pull request by jordan8037310**
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [X] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [X] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)? 

-----
No output from brew audit.

### CODE REVIEW

**Comment by javian** [comment]
Thanks for the submission @jordan8037310 - next time you don't have to remove the bottle block since the bot will take care of it.

**Comment by javian** [comment]
A while back I checked in with the developers https://github.com/hechoendrupal/DrupalConsole/issues/2121 and I suggested we make the 1.0 release a devel release. Do you think that would make sense since the 0.11 release is still the one marked as stable ?

**Comment by javian** [comment]
@jordan8037310 this is linked to a different software (repo) - is it really the same ?

**Comment by jordan8037310** [comment]
@jmolivas, @enzolutions, care to comment on the split from the core and launcher projects?

**Comment by jmolivas** [comment]
@javian yes the repo change is correct.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
Thanks for the submission @jordan8037310 !

**Pull request closed without merging**
