### PR TITLE
enable WebP support in gd

### LINKED ISSUE #3645: How can I enable WebP support in GD library?
## Description

How can I enable Webp support in GD library?
## Context and Logs

| Parameter | Value |
| --- | --- |
| **OS X Version:** | 10.12 |
| **Homebrew Version:** | 1.0.4 |
| **PHP Version in use:** | 7.0.11 |
| **Xcode Version:** | 8A218a |

finish in PR https://github.com/Homebrew/homebrew-php/pull/3647

### PR DESCRIPTION
**Pull request by jk2K**
- [ x ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew-php/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally prior to submission with `brew install <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ x ] Does your submission pass `brew audit --strict --online <formula>` (after doing `brew install <formula>`)?

---

fix #3645

### CODE REVIEW

**Comment by javian** [comment]
It looks like this is not supported in all php versions `(PHP 5 >= 5.5.0, PHP 7)` so you need to take that into account.

**Comment by javian** [comment]
@BrewTestBot test this please

**Comment by javian** [comment]
@jk2K have you taken a look at the changes I requested ?

**Comment by javian** [comment]
@jk2K do you want to have another go at this ?

**Comment by jk2K** [comment]
Sorry, I am very busy this time, I have looked at the changes you requested. But I do not have time to fix it

**Comment by javian** [comment]
Closing this issue. We can revise it when we create the split for the SAPIs and include it then.

**Pull request closed without merging**
